### ISSUE TITLE
Feature request: ability to fully customize outputs from reporters

### ISSUE THREAD

**Issue by gentunian** [sverweij/dependency-cruiser#204]
### Context

Currently, `dot` reporter (a.k.a. dot output type) output can't be fully customized. To do so, you will need to invoke `dot` external program like so:

`dependency-cruiser -T dot ... | dot -Gcompound=true -Gedgesep=1.2 -Garrowsize=0.3 ...`

Although this is possible to overcome with the external tool as mentioned above, it would be nice to be possible for each reporter to receive custom options and each one manage them as needed.

### Expected Behavior

Creating a `dot` script with custom arrow size and edge separation would be:

`dependency-cruiser --custom-output-dot-arrowsize=0.4 --custom-output-dot-edgesep=1.2 -T dot ...`

It will create a `dot` script with custom arrowsize and edgesep values.

### Current Behavior

Currently it's not possible to fully customize `dot` output. Although it has a coloring scheme option, I think this is a general and more powerful approach, that could also be extended to every reporter.

### Possible Solution

It seems quite simple at the first glance from the [main/index.js](https://github.com/sverweij/dependency-cruiser/blob/develop/src/main/index.js#L44) file reporters are being invoked. So they could be invoked with a sanitized `pOptions` variable. I think a prefix name should be think of, i.e., `--custom-output-[outputType]-[everything-else]`).

```
function cruise(pFileDirArray, pOptions, pResolveOptions, pTSConfig) {
  pOptions = normalizeOptions(validateOptions(pOptions));

  if (Boolean(pOptions.ruleSet)) {
    pOptions.ruleSet = normalizeRuleSet(validateRuleSet(pOptions.ruleSet));
  }

  const lExtractionResult = extract(
    normalizeFilesAndDirs(pFileDirArray),
    pOptions,
    normalizeResolveOptions(pResolveOptions, pOptions, pTSConfig),
    pTSConfig
  );
  pOptions = manage --custom prefix here and normalize output as a key/value meaningful for each reporter
  return report.getReporter(pOptions.outputType)(lExtractionResult, pOptions);
}
```

### Considered alternatives

One alternative is using the external program `dot`, for example:

`dependency-cruiser -T dot ... | dot -Gcompound=true -Gedgesep=1.2 -Garrowsize=0.3 ...`

but this only takes into account the `dot` output, and luckily you can overcome that. But, I found that not always `dot` can parse the output generated by dependency cruiser. And if I pass the same dot output to [viz.js](https://github.com/mdaines/viz.js) it could generate a svg correctly, in which case `dot` will segfault.

So, there's no way to manipulate the output in that case.

Alternatives to other outputs may be as same as complicated or even impossible.

**Comment by sverweij** [comment]
Hi @gentunian sorry for taking such an extremely long time to respond to your (well documented and researched!) feature request.

There's a PR (#225 ☝️) that implements this feature, but with options in the dependency cruiser configuration file instead of with command line parameters (based on my experience with a similar feature in [state-machine-cat](https://github.com/sverweij/state-machine-cat#command-line-interface) combined with the additional complexity of conditional formatting that was already in place that seemed the most obvious route).

> If you want to you can try it - I've published it as `dependency-cruiser@beta` on npm

It not only implements the general (graph, node and edge) attributes, but also enables to configure any module and dependency based on [module properties](https://github.com/sverweij/dependency-cruiser/blob/develop/types/cruise-result.d.ts#L16) and [dependency properties](https://github.com/sverweij/dependency-cruiser/blob/develop/types/cruise-result.d.ts#L73) respectively with everything graphviz dot has to offer for nodes and edges (shapes, colors, arrowheads, fontnames, ...).

> I'm in the process of adding some samples to illustrate the possibilities

### Does this fix the root cause of your issue though?

From your request I get the impression there's a need behind the feature request. Is it that sometimes the dot's don't render (e.g. for big code bases) or do you want to tweak the output for better readability (if you have tweaks that do - consider me interested 😃)?

_In the first case_: GraphViz can't process every syntactically correct dot thrown at it. Especially (very) large graphs with lots of groups in them. I expect viz.js to have the same problem as it's just GraphViz compiled to javascript.

In some cases it can be solved by tweaking a few parameters, but in general reducing the graph (I've encountered this often enough there's an [FAQ entry](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-the-graph-dependency-cruiser-generates-is-humoungous-and-i-cant-follow-the-lines-very-well-what-can-i-do) on it.

> => If you have an example of a reasonably sized graph dot cannot render because dependency-cruiser generated something syntactically incorrect I'm _very_ interested as I consider that a bug in dependency-cruiser.

_In the second case_: with this PR you should be able to tweak to your heart's content.

**Comment by gentunian** [comment]
hi @sverweij 

thanks for your reply! Considering your question about the need: it was when I wanted to tweak the graph a little bit and I found that it was not possible without using external tools. The reason why is almost like you imagined, but I tried to abstract that issue just because nevertheless it was a missing feature.

Great news then!
