### ISSUE TITLE
[Question] IDE integration

### ISSUE THREAD

**Issue by tmtron** [sverweij/dependency-cruiser#272]
Is there a way to show dependency errors directly in IDEs (e.g. IntelliJ)?

I woud be great if the checks could be run in background and the IDE could show the errors directly in the editor on the fly - e.g. like TsLint/EsLint checks

Or maybe these checks could even be called via an EsLint rule (e.g. like the [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import) plugin)

**Comment by sverweij** [comment]
Hi @tmtron - that is a cool idea! I don't know of the existence of any IDE integration (IntelliJ or otherwise) at this time that shows dependency errors in a fashion akin to linter plugins. Dependency-cruiser does have a documented [API](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/api.md), though. With some acuity in the IDE's plugin system it shouldn't be too hard to write such an integration. Enterprising folks have made e.g. an integration with [vscode](https://github.com/waningflow/CodeRoad), and [other](https://github.com/sverweij/dependency-cruiser/issues/128) [folks](https://github.com/Himenon/code-dependency) have [used](https://github.com/MichalZalecki/codechecks-dependency-cruiser) it for server side integrations.



> B.t.w. if you're into the JetBrain's tool chain - the output format `teamcity` was made for Team City.

### eslint plugin

Also a good suggestion. To the best of my knowledge that doesn't exist yet.

I _did_ consider writing an eslint plugin before, but at the time rejected the idea. Time lacked, but  there were other considerations as well. Dependency-cruiser already supported 4 languages, eslint at the time only one. I also didn't see how to do checks that run over more than one dependency (reachable, circular) while remaining decently performant.

I've been looking into writing an eslint plugin again recently, though (for different purposes), and with some pragmatism it should be possible to have rule configurations checked with an eslint plugin. It will still require quite a time investment, though...

**Comment by tmtron** [comment]
Thanks @sverweij for the answer and escpecially for links to the external tools.

**Comment by namoscato** [comment]
👋🏻 @sverweij, thank you for this great project!

I was curious if there has been any update on an IDE integration or if you are aware of any ESLint plugins? We heavily rely on ESLint's early development feedback in IDEs, which would be great to maintain ahead of opening pull requests / CI checks.
