### ISSUE TITLE
doNotFollow in API works unexpectedly

### ISSUE THREAD

**Issue by electrovir** [sverweij/dependency-cruiser#281]
Maybe this isn't actually a bug and I just misunderstand the purpose of this option? If that's the case feel free to correct my expectations 🙂

### Expected Behavior

Including `doNotFollow: 'node_modules'` in the API options adds the list of dependencies my modules have on npm packages but doesn't include those npm packages in dependency traversal.

### Current Behavior

Including `doNotFollow: 'node_modules'` adds the list of npm package dependencies but _also_ traverses all of `node_modules`.

### Steps to Reproduce

[repro repo](https://github.com/electrovir/test-dependency-cruiser-do-not-follow/blob/master/test.ts)
1. Compare `cruise(['./'], {doNotFollow: 'node_modules'}).output` with `cruise(['./']).output`: there appears to be no difference.

### Context

Wishing to get a list of dependencies (including npm package dependencies) but without traversing `node_modules` because that folder gets huge and I don't care about the dependencies in there 🙂

### Your Environment

* Version used: `8.2.0`
* Node version: `12.16.0`
* Link to your project: [https://github.com/electrovir/test-dependency-cruiser-do-not-follow/blob/master/test.ts](https://github.com/electrovir/test-dependency-cruiser-do-not-follow/blob/master/test.ts)

**Comment by sverweij** [comment]
hi @electrovir - thanks for reaching out about this. I get why dependency-cruiser's behaviour puzzles you here. I'll at least have to describe this somewhere or I should rethink how this works.

There's a few steps dependency-cruiser takes when you fire it of:
- gather all files specified as an argument, filtering out the stuff in `exclude` and that which is not in `includeOnly`.
- starting from the gathered files: crawl all dependencies it can find. Crawling stops when a module matches  `doNotFollow` rule or a modules dependency matches either exclude or includeOnly. 
- apply any rules over the result & report it.

unlike the `exclude` and `includeOnly` options, dependency-cruiser uses the `doNotFollow` option in the crawl step only. 

So when you specify `'./'` as an argument it'll faithfully gather everything in the folder - your `test.ts`, `package.json` - but also your `node_modules`... I haven't had a lot of people bump into yet, I guess because mostly sources live in their own folders (`src`, `lib`, `app`, `test` ...) and specifying automatically leaves out any node_modules.

What can you do to mitigate this behaviour ?

Assuming your files will keep living in the root of your project:
- If you still want to see relations to node_modules: specify the files you want to start your crawl with with a glob pattern e.g. `*.ts`, or `*.{js,ts,json}` as an argument.
- If you're just interested in the internal structure and not so much in relations to node_modules, use `exclude` (and pass `^node_modules` to it)

HTH ...

**Comment by electrovir** [comment]
Okay, that all makes sense. Thanks for the explanation!

> If you still want to see relations to node_modules: specify the files you want to start your crawl with with a glob pattern e.g. *.ts, or *.{js,ts,json} as an argument.

This does allow me to do what I want with the simple example repo I linked. However, what I'm really getting at is a bit bigger. I want to use this in a mono-repo that has multiple subfolders which contain their own `package.json` and thus their own `node_modules` directories. The solution above doesn't work in that situation because it in order to get all subdirectories I need a `**` glob pattern, which then includes `node_modules`. (The simple repo I created is simply a minimal case that shows the issue I'm having.)

Here's an example of a file structure I might be interested in:

```
./
    project-a/
        node_modules/
            ...
        package.json
        src/
            some-code.ts
            other-code/
                more-code.ts
    project-b/
        node_modules/
            ...
        package.json
        maybe-not-named-src/
            project-b-code.ts
            more-project-b-code.ts
```

I would like to "cruise" the 4 `.ts` files shown here (or any other files added around them)  while also getting a list of their dependencies on anything in `node_modules` but _without_ cruising anything in `node_modules`. Does that make sense?

After reading your explanation I've been playing around with using negative glob patterns for the first input to `cruise()` (something crazy like `*/**/!(node_modules)/**/*.ts`) but I have not yet been able to concoct a pattern that does what I want 😢

**Comment by sverweij** [comment]
Hi @electrovir - this is similar to the mono-repo I've worked with over the last years. We've been using something like `packages/*/{src,lib}` as a pattern because that's where the sources typically resided. For also including all cases `maybe-not-named-src` some glob magic will be required indeed. 

As a first try I've used the pattern `"packages/*/!(node_modules)"` - and that works as expected, in the sense that scans everything in packages/*/, except node_modules. You might want to include some extra inclusion patterns there for good measure - `dist` (or wherever generated javascript goes), `coverage` might be good candidates, but maybe also config files...

```javascript
const lResult = cruise(["packages/*/!(node_modules|dist|coverage)"], {
  doNotFollow: "node_modules",
  outputType: "text", // or whatever reporter you'd want to use
}).output;
```
> under the hood dependency-cruiser uses [glob](https://github.com/isaacs/node-glob), for argument matching.
> You can exercise that with [minimatch](https://github.com/isaacs/minimatch) for quick
> feedback cycles on what patterns yield what result

=> Just interested: what's the reason to use the API instead of the cli?

**Comment by electrovir** [comment]
`"packages/*/!(node_modules)"` only works if all `node_modules` directories are at the same level in the directory structure, right? (At least that's what is happening for me.) Specifically, if `node_moduels` is within any direct subdirectories of `packages` but if they're in deeper subdirectories then they won't be ignored.

Why using API:
I'm using `dependency-cruiser` to list dependencies, which I'm playing around with inside of TypeScript. I'm not using the validation features of `dependency-cruiser`. I looked into the code to see if there is another package you use to get this list but your output is exactly what I want so I decided to stick with using `dependency-cruiser`. Is there a different package better suited to this specific purpose?

I think I'll be fine without having `node_modules` dependencies listed, I wanted to see if it was possible and to double check that I wasn't missing something in the documentation 👍

**Comment by sverweij** [comment]
hmm @electrovir - I think you got a point there. If the monorepo is somewhat standardised it shouldn't be a problem, but in practice that's often not going to be the case. Entropy is real :-) 

I've published a beta version that with your initial call (`cruise(['./'], {doNotFollow: 'node_modules'}).output`) should yield what you'd expect in the first place, without the need for globbing trickery: `dependency-cruiser@8.3.0-beta-1`. You can install it like you installed the 

=> Could you give it a spin? (And all feedback is welcome)

### background

There's two courses of action: document the behaviour + workarounds. Or change the behaviour to be more intuitive. In the beta version the  _gather all files_ step disregards the files that match the pattern passed as _doNotFollow_. As far as I can see this has no backwards compatibility implications (because dependency-cruiser will encounter the doNotFollows anyway in the `crawl all dependencies` step), but will make the doNotFollow (--do-not-follow) option a lot easier to use.

> As to your question whether there is another/ better package to just run through all
> dependencies... As far as I know dependency-cruiser is the only package that where 
> module dependencies are concerned _catches them all_ - including some types of
> dynamic imports and custom require functions.

**Comment by electrovir** [comment]
`dependency-cruiser@8.3.0-beta-1` does the trick! Now `cruise(['./'], {doNotFollow: 'node_modules'})` shows imports from `node_modules` in relevant dependency lists but the `node_modules` directory itself isn't traversed! 🎉 Thanks! 😀 I also noticed and really like that the `dependency.module` property tells me name name of the npm package that is being imported!

I, of course, would vote for the `change the behaviour to be more intuitive` option but I don't know anything about how this might affect current users.

> As far as I know dependency-cruiser is the only package that where
module dependencies are concerned catches them all

When I was looking through the code I actually noticed this, which led me to me stick with the dependency-cruiser API instead of trying to find a lower level package. 🙂

**Comment by sverweij** [comment]
> I, of course, would vote for the change the behaviour to be more intuitive option but I don't know > anything about how this might affect current users.

Second that - it should've worked that way from the outset (so thanks for realising this, raising it as an issue and being tenacious!). I doubt it is going to affect a lot of current users - or even whether it would classify as a breaking change. But even if it is, dependency-cruiser will get a major-bump - which will have to happen soon anyway because node 8 support is becoming untenable and needs to be dropped.
