### ISSUE TITLE
Use glob for CLI arguments

### ISSUE THREAD

**Issue by ajafff** [sverweij/dependency-cruiser#32]
Currently the CLI doesn't support globbing. That's not a problem on linux shells as they already expend glob patterns.
If I wanted to use the same command on Windows however, I get an error like `ERROR: Can't open 'packages/*/src' for reading. Does it exist?`.
Because of this, I cannot really use this package on a windows CI to test my dependencies.

It would be great if you could consider using `glob` to find the files.

As a side effect that also allows using extglob and globstar features even if the shell doesn't support that. You only need to wrap the glob pattern in quotes and let depcruise do the globbing instead of the shell.

**Comment by sverweij** [comment]
Hi @ajafff first of: thanks for reporting this and the other three issues - the level of details is excellent to work with! I'll respond to them one by one in context, but here's some stuff that goes for all 4:

### ordering
I can't pick them all up at the same time I'm going to need to order them. This is my working assumption - please correct me:
1. #32 (Use glob for CLI arguments) - because that is an issue that prevents cross platform use of arguments that in some scenario's is blocking. 
2. #33 (resolve symlinks) - because it's a bug, 
3. #34 (introduce a severity level for the 'allowed' set of rules) - new feature 
4. #35 (use closest package.json) - improve support for mono repos

(I don't guarantee I'll pick em up in that order; if there's low hanging fruit that takes only an hour to fix that might get attention first). 

That said - a helping hand is welcome.

### releases
Once an issue is fixed I'll release it. First as a beta, and if you're satisfied as well as a regular _latest_ (i.o.w. I won't wait until everything is done before releasing fixes).

**Comment by sverweij** [comment]
B.t.w about _this_ issue: your expectation dependency-cruiser should work cross platform is correct. I wasn't aware of the limitations on windows (or of the differences between sh & zsh :eyes:) - so there's nothing to it than putting a layer of abstraction between it; `glob` (your suggestion) seems the perfect fit. 

Working on it :-)

**Comment by sverweij** [comment]
@ajafff dependency-cruiser version 2.14.0-beta-0 with PR #36 (which is a fix for this issue) is on npmjs.org since a few minutes.

Let me know if it works for you.

**Comment by sverweij** [comment]
Published 2.14.0 - which === 2.14.0-beta-1 except for the version number & npm tag - which closes this issue (on to PR reviewing then ...)
