### ISSUE TITLE
Issue: collapsePattern ignored for ddot / archi reporters

### ISSUE THREAD

**Issue by alecf** [sverweij/dependency-cruiser#331]
### Expected Behavior

Adding `collapsePattern` should reduce results as per the docs.

### Current Behavior

Changing `collapsePattern` has zero effect on the `ddot` and `archi` reporters. I'm able to tweak 

### Possible Solution

n/a

### Steps to Reproduce (for bugs)

1. set `collapsePattern` to something simple like `'node_modules.*'`
2. set output with `-T 'archi'` or `-T 'ddot'`
3. Note that `node_modules` isn't collapsing
4. Set the output to `'dot'`
5. Note that `node_modules` is collapsed to a single node

### Context

I'm unable to use `ddot` or `archi` outputs :/

### Your Environment

- Version used: 9.8.1 (also saw in 9.8)
- Node version: 14.3
- Operating System and version: Linux
- Link to your project: (internal)

**Comment by sverweij** [comment]
Hi @alecf thanks for taking the time to raise this issue. 

I've retried running the `archi` and `dot` reporters with collapse patterns and can't seem to reproduce the issue, though.

There are a few things to note about collapse patterns:
1. The _do_ work for `archi` and `dot`, but not for `ddot` (the folder level one). At the time this was implemented the reasoning was that for the folder level one the modules are already collapsed (to folders) so there wouldn't be a need. Let me know if you think otherwise, though!
2. The collapse patterns in a way that currently is not apparent from the documentation (so I'll need to fix that). Dependency-cruiser uses the match result of collapsePattern to extract the the pattern to collapse to from file names. 

To collapse to folders just below node_modules, you'd use a pattern like `node_modules/[^/]+`. 

module| collapses to ...
---|---
node_modules/aap/noot.js | node_modules/aap
node_modules/mies/wim.js |node_modules/mies
node_modules/mies/zus.js | node_modules/mies
node_modules/mies/jet.json | node_modules/mies

To collapse to node_modules/ (and not to something below it) directly, you'd use the pattern `node_modules/`

module| collapses to ...
---|---
node_modules/aap/noot.js | node_modules/
node_modules/mies/wim.js |node_modules/
node_modules/mies/zus.js | node_modules/
node_modules/mies/jet.json | node_modules/


If you'd use a pattern like `node_modules.*`, it would extract the exact file name that would be put into it, resulting in no effectively no collapsing at all:

module| collapses to ...
---|---
node_modules/aap/noot.js | node_modules/aap/noot.js
node_modules/mies/wim.js |node_modules/mies/wim.js
node_modules/mies/zus.js | node_modules/mies/zus.js
node_modules/mies/jet.json | node_modules/mies/jet.json

... 

HTH

If with adapted patterns you still experience a disturbing lack of collapsing; don't hesitate to holler (I might be asking for a minimal reproduction sample, though...)
