### ISSUE TITLE
Feature request: consider jsconfig base Url into resolved attribute

### ISSUE THREAD

**Issue by henriquecaraujo** [sverweij/dependency-cruiser#334]
First of all, I would like to thank the entire community that maintains dependency-cruiser <3

It would be nice if dependency-cruiser reads the dependency paths according to the baseURL defined in jsconfig.json

### Context
Some js / jsx projects that we analyze dynamically have the file jsconfig.json with the baseURL assigned to the src folder. When analyzing these projects with dependency-cruiser it's not possible to follow them because the attribute followable returns false.

### Expected Behavior

After analyzing the directory informing jsconfig's path file via compilerOptions, the modules can be followed

### Current Behavior
There's no option for jsconfig, only tsconfig

### Possible Solution
Maybe concatenate baseUrl as prefix in resolved  attribute?

### Considered alternatives
Current we are skiping projects that has jsconfig

**Comment by sverweij** [comment]
hi @henriquecaraujo thanks for bringing this to the attention. 

If with jsconfig you mean the [config format as used by vscode](https://code.visualstudio.com/docs/languages/jsconfig) for javascript projects, that should already work out of the box. That is, provided dependency-cruiser has the typescript compiler at its disposal (= installed at the same spot dependency-cruiser is installed). This is because the typescript compiler is the only engine I know of that correctly parsers (js|ts)Config.json's and all their properties (like inheritance from other configs) - and I bet vscode is using that under the hood as well.

Just pass it in the configuration in the [`tsConfig`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#tsconfig-use-a-typescript-configuration-file-project) key or on the command line with --ts-config.

Let me know if it works for you!

**Comment by henriquecaraujo** [comment]
Hey @sverweij , thanks for you reply and I'm very sorry for the delay in replying.
We're using API to analyze our project, so I can't pass --ts-config as well. There's any possibility to pass that param in API?

**Comment by sverweij** [comment]
hi @henriquecaraujo yep that's possible. It's slightly klunky, though - and (I now see) - not yet documented. 


### When no typescript compiler is available

=> likely this will suffice in your situation

```javascript
const depcruise = require('dependency-cruiser');

const result = depcruise(
    ["src"],
    {
        tsConfig: {
          "fileName": "path/to/your/tsconfig.json",
        },
        // ... your other regular dependency-cruiser options
    },
    {
        // ... any options to pass to the resolver 
    }
)
```

## When a typescript compiler is available 

=> In your situation you might not need this

```javascript
const depcruise = require('dependency-cruiser');

const result = depcruise(
    ["src"],
    {
        tsConfig: {
          "fileName": "path/to/your/tsconfig.json",
        },
        // ... your other regular dependency-cruiser options
    },
    {
        // ... any options to pass to the resolver 
    },
    {
        // ... your parsed tsConfig/ jsConfig to feed the typescript compiler
        options: {
          baseUrl: ".",
          module: "es6",
          // ... 
        },
    }
)
```

Parsing the tsConfig/ jsConfig into thing the typescript compiler can ingest is a bit convoluted - and currently part of the `cli` (and not of the API) - see [parse-ts-config.js](https://github.com/sverweij/dependency-cruiser/blob/develop/src/cli/parse-ts-config.js).
