### ISSUE TITLE
Feature request: Add a mermaid reporter

### ISSUE THREAD

**Issue by dagadbm** [sverweij/dependency-cruiser#353]
### Context

It would be nice if the dependency graph could be generated using mermaidJS (assuming its possible)

### Expected Behavior

Output a .md file with the mermaid syntax on it
```mermaid
graph
 ...
 ...
```

**Comment by dagadbm** [comment]
I guess the main "problem" would be to drop the graphviz dependency and have the graph part of the documentation as text (gitlab even reads mermaid for you automatically as well)

Im guessing the flowchart one (https://mermaid-js.github.io/mermaid/#/flowchart) would probably the most similar one to what this tool does.

i am testing this tool out for now but I was surprised for it to not support such a well known (at least it seems like it) project.

**Comment by sverweij** [comment]
For anyone who has an interest in picking this up - dependency-cruiser now has a plugin mechanism for reporters that should make developing and maintaining reporters easier - see the [_How do I add a new output format_](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-how-do-i-add-a-new-output-format) section in the FAQ for a starting point.

**Comment by fabiospampinato** [comment]
> To research: does it scale to ~200 nodes & ~300 edges?

Maybe, but it would take a while to generate the diagram for thousands of nodes, mermaid is very slow in my experience, it touches the DOM too much.

**Comment by sverweij** [comment]
I guess that with #599 this issue can be considered as _fixed_. For future visitors; it's currently implemented as a plugin, which can be invoked e.g. thusly:

```sh
depcruise src --config .dependency-cruiser.js --output-type plugin:dependency-cruiser/mermaid-reporter-plugin
```

It isn't as feature rich as the the `dot` reporters - and _can't_ be due to limitations in mermaid (see [comment above](https://github.com/sverweij/dependency-cruiser/issues/353#issuecomment-678693190)). But if the goal is to visualise the dependency-graph, without highlighting detected errors, warnings, cycles etc. this might serve.
