### ISSUE TITLE
Not a bug or a feature: should reexport be recognized as a dependency?

### ISSUE THREAD

**Issue by perottilds** [sverweij/dependency-cruiser#378]
### Summary / Context

I was fiddling with depcruiser to make it easier finding out whether a page has or not some dependency and stumbled upon the fact the `export { default as Something } from './SomeWhere.component';` couldn't find the matching file even though it's a sibling of the file reexporting it.

The question is: is it not being recognized by depcruiser because of the reexport or is it because the file has an unexpected extension? Please notice the file has the name 'SomeWhere.component.tsx' thus tsx can be omitted.

### Environment

- Version used: 9.15.0
- Node version: v12.18.4
- Operating System and version: Linux 5.8.11-1-MANJARO x86_64 GNU/Linux
- Link to your project:

**Comment by perottilds** [comment]
Quick findings: its both actually. But mostly the depcruiser is having a hard time with reexports.

**Comment by sverweij** [comment]
hi @perottilds I've tried to reproduce the issue in [dependency-cruiser-repro-repo/378](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/378) with your input, but it just seems to work fine. It should as support for it .tsx and exports 

What might be the root cause:
- Is the typescript compiler installed in the same folder as where you're running dependency-cruiser from?
  (you can check by running depcruise --info)
- Does dependency-cruiser know where your tsconfig.json lives? You can tell it by creating config (with depcruise --init) and using it by passing it with the --config option (`depcruise folders_you_want_to_scan --config .dependency-cruiser.js`) 
- (A less convenient option os to  pass the tsconfig.json to the --ts-config option (`depcruise folders_you_want_to_scan --ts-config tsconfig.json`)

If with this it still doesn't work let me know. In that case I probably need exact command invocation you used, the .dependency-cruiser you used and the version of the typescript compiler.

**Comment by perottilds** [comment]
I think you have something going there. Indeed the tsconfig resides somewhere else. I'll try your suggestion

**Comment by perottilds** [comment]
I'm closing it for now. I'll reopen it if I get into any trouble

**Comment by perottilds** [comment]
yeah the issue was that I was using the globally installed depcruiser which had no access to the tools used.
`depcruiser --info` did the trick to realize it
it works just fine and thanks for this fine library
