### ISSUE TITLE
Not a bug or a feature: Takes too much time for reading files (ms-windows)

### ISSUE THREAD

**Issue by tvolodimir** [sverweij/dependency-cruiser#386]
Cruiser is very slow

files: 507
size: 1.988MB

I have following log:
```
  elapsed heapTotal  heapUsed after step...
   1591ms      70Mb      48Mb start of node process
      9ms      70Mb      48Mb parsing options
    179ms      75Mb      49Mb parsing rule set
      1ms      75Mb      49Mb making sense of files and directories
      7ms      75Mb      49Mb determining how to resolve
 132729ms     140Mb      95Mb reading files
      2ms     140Mb      95Mb analyzing
     22ms     140Mb      98Mb analyzing: cycles
      8ms     140Mb      99Mb analyzing: orphans
      1ms     140Mb      99Mb analyzing: reachables
      1ms     140Mb      99Mb analyzing: add focus (if any)
    119ms     140Mb      93Mb analyzing: validations
      7ms     140Mb      94Mb reporting
      3ms     140Mb      94Mb really done (134678ms)
```

### Summary

I am wondering if there are some way to find out why this is so slow. For example get more details log of what files was read and read time.

### Environment

- Version used: 9.16.0
- Node version: v12.13.0
- Operating System and version: Windows 10
- Link to your project: -

**Comment by sverweij** [comment]
Hi @tvolodimir thanks for sharing this! 2 minutes for ~500 files is indeed _a lot_ slower then what I'm used to - so something interesting is afoot. 

The `reading files` step is doing what it says on the tin - reading modules from disk and parsing them. At this moment there's not an _extra strong_ logging mode to show more details, but I'm very interested in what is going on:

- Could you share the command line invocation + the dependency-cruiser config you were using to get this result?
- What's the type of disk you're running on (SSD or spinning disk)? 
- The dot in the 1.988 you mention - is that a thousands separator (meaning 1988Mb or almost 2Gb) or a decimal separator (so the total size is closer to 2Mb)?

> I just ran a slightly older (and slower) version of dependency-cruiser against a small part of a mono repo and that took 50s for the whole cruise (6500 files/ 25000 dependencies, on an SSD, but with an active on-access virus scanner). In the past I did get multi-minute results when I accidentally scanned all node_modules besides the stuff I was actually interested in, but as you mention the 500 files explicitly, I assume that's not what you are facing.

**Comment by tvolodimir** [comment]
It's 2 MB, And all files are written in TS, imports are to other ts files, package modules, and am using ts aliases, that is well resolved by cruiser.

I was debugging over sources. and found that from `gatherInitialSources` a get file paths with '\' slashes
and all other calls from extractRecursive give me paths with '/' slashes.
So improvement number one, that brings two-time fast work is `gatherInitialSources.map(pathToPosix)`

Going deeper I fount that all calls of `extractDependencies` takes 1786ms and `*.map(addResolutionAttributes(..))` takes 282018ms. So all calls of `resolve` take almost of time of the `reading files` step.
3742 calls of `resolve` took 278370 ms
relative deps take 80ms+ first time, seconds 1-3 ms
ts alias deps to assets deps take 170ms+ first time, seconds 60-70 ms
ts alias deps to ts file deps take 270ms+ first time, seconds 160-170 ms
package deps  take 25-40ms

```ts
pResolveOptions = {
  "symlinks": true,
  "extensions": [
    ".ts",
    ".tsx",
    ".js",
    ".json"
  ],
  "modules": [
    "node_modules",
    "node_modules/@types"
  ],
  "exportsFields": [],
  "plugins": [],
  "tsConfig": "./tsconfig.json",
  "externalModuleResolutionStrategy": "node_modules",
  "combinedDependencies": false,
  "mainFields": [
    "module",
    "browser",
    "main"
  ],
  "fileSystem": {...},
  "useSyncFileSystemCalls": true
}
```

I fill, that `resolve` can be optimized, as even to take more than 10ms for resolve is too much from my point of view

**Comment by tvolodimir** [comment]
UPD:
## From start
```ts
// webpack.config
module.exports = {
...
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".json"],
    mainFields: ["module", "browser", "main"],
    symlinks: true,
    plugins: [],
  },
...
```
```js
pResolveOptions = {
  "symlinks": true,
  "extensions": [
    ".ts",
    ".tsx",
    ".js",
    ".json"
  ],
  "modules": [
    "node_modules",
    "node_modules/@types"
  ],
  "exportsFields": [],
  "plugins": [],
  "tsConfig": "./tsconfig.json",
  "externalModuleResolutionStrategy": "node_modules",
  "combinedDependencies": false,
  "mainFields": [
    "module",
    "browser",
    "main"
  ],
  "fileSystem": {...},
  "useSyncFileSystemCalls": true
}
}
```
`3742 calls of resolve took 278370 ms`
### Added fix** `gatherInitialSources(..).map(t=>pathToPosix(t))` 
`1981 calls of resolve took 181802 ms`
### Removed webpack.config
```ts
pResolveOptions = {
  "symlinks": false,
  "extensions": [
    ".js",
    ".cjs",
    ".mjs",
    ".jsx",
    ".ts",
    ".tsx",
    ".d.ts",
    ".coffee",
    ".litcoffee",
    ".coffee.md",
    ".csx",
    ".cjsx",
    ".vue"
  ],
  "modules": [
    "node_modules",
    "node_modules/@types"
  ],
  "exportsFields": [],
  "plugins": [
    {
      "source": "described-resolve",
      "target": "resolve",
      "extensions": [
        ".js",
        ".cjs",
        ".mjs",
        ".jsx",
        ".ts",
        ".tsx",
        ".d.ts",
        ".coffee",
        ".litcoffee",
        ".coffee.md",
        ".csx",
        ".cjsx",
        ".vue"
      ],
      "log": {},
      "baseUrl": "./src",
      "absoluteBaseUrl": "D:\\1\\dev\\isb\\dt\\packages\\design_tool\\src"
    }
  ],
  "tsConfig": "./tsconfig.json",
  "externalModuleResolutionStrategy": "node_modules",
  "combinedDependencies": false,
  "fileSystem": {},
  "useSyncFileSystemCalls": true
}
```
`1981 calls of resolve took 554715 ms`

**Comment by sverweij** [comment]
hi @tvolodimir thanks for your deep-dive - I'll be trying some of your suggestions. The early mapping to posix paths looks interesting - my hunch is that it's mostly relevant for performance on windows machines (I'll test that). The difference in lookup times for relative, aliased and package deps is interesting to see. It's in line with my expectations, except for the aliases (270ms a.c.t. 80ms in the same situation is pretty stark). 

There's some options that will positively (and sometimes dramatically) influence the speed at which the dependency-cruiser runs, which I don't see in the options passed in the examples above (but which you might have configured elsewhere? feel free to share it)

- `tsPreCompilationDeps`  
if you switch this to `true` dependency-cruiser will directly use the AST the typescript compiler generates - which is a lot faster than when it's on `false` which first transpiles the typescript to javascript before making it into an AST (typically about a 1.8 - 2x speed-up). You will probably see this reduction back in the _resolve_ step.
- filter options (e.g. `doNotFollow`, `includeOnly` or `exclude`)   
These options help limiting the cruise of files you might not be interested in. E.g. `--init` sets `doNotFollow` to `node_modules` by default, which prevents an exhaustive scan of any node_module's internal sources, which will take _a lot_ of time (then again if you're interested in exactly that -> leave it on). 
- [tweak enhanced-resolve's cache duration](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#enhancedresolveoptions)    
Last resort option for specialised cases like large-ish repo's (> 5000 modules), running on spinning disks, a-typical module sizes/ dependency-counts etc.

The alt webpack config is interesting. It could be a bit faster because TsConfigPathsPlugin (which overrides the one dependency-cruiser sets) only attempts scans of 2 extensions (.ts and .tsx - webpack plugins don't have access to the resolve.extensions). The instance of TsConfigPathsPlugin dependency-cruiser loads by default (in [main/resolve-options/normalize.js](https://github.com/sverweij/dependency-cruiser/blob/1b53650100ddf48e63d6d192883b9ec301bf7d85/src/main/resolve-options/normalize.js#L67)) makes sure it takes all resolve.extenions into account - in your case 4 of them.

You mentioned there's about 500 files 
- what's the amount of files that was eventually scanned?
- what's the number of dependencies?

> As an aside: it seems you're using dependency-cruiser's API - I'm interested to know why!

**Comment by tvolodimir** [comment]
I guess it's the best I can get for now. 
```
  elapsed heapTotal  heapUsed after step...
   3069ms      70Mb      48Mb start of node process
      9ms      70Mb      49Mb parsing options
    192ms      75Mb      53Mb parsing rule set
      1ms      75Mb      53Mb making sense of files and directories
      5ms      75Mb      54Mb determining how to resolve
  64520ms     221Mb     192Mb reading files
      2ms     221Mb     192Mb analyzing
     96ms     221Mb     196Mb analyzing: cycles
      4ms     221Mb     196Mb analyzing: orphans
      1ms     221Mb     196Mb analyzing: reachables
      1ms     221Mb     196Mb analyzing: add focus (if any)
    143ms     222Mb     198Mb analyzing: validations
      3ms     222Mb     199Mb reporting

√ no dependency violations found (504 modules, 1731 dependencies cruised)

      2ms     222Mb     199Mb really done (68046ms)
```
```js
 options: {
    includeOnly : '^src/modules/',
    doNotFollow: {
      dependencyTypes: [
        'npm',
        'npm-dev',
        'npm-optional',
        'npm-peer',
        'npm-bundled',
        'npm-no-pkg'
      ]
    },
    tsPreCompilationDeps: true,
    tsConfig: {
      fileName: './tsconfig.json',
    },
    webpackConfig: {
      fileName: 'fake-webpack.config.js',
    },
    exoticRequireStrings: ['globalThis.require'],
    enhancedResolveOptions: {
      cachedInputFileSystem: {
        cacheDuration: 600000
      }
    },
  }
```
```ts
// fake-webpack.config.js
var TsconfigPathsPlugin = require("tsconfig-paths-webpack-plugin");
module.exports = {
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".json"],
    mainFields: ["module", "browser", "main"],
    symlinks: true,
    plugins: [
      new TsconfigPathsPlugin({
        configFile: require("path").join(__dirname, './tsconfig.json'),
      }),
    ],
  },
}
```

> As an aside: it seems you're using dependency-cruiser's API - I'm interested to know why!

Not really, but I would use if you will have public API,
It's a bit complicated to set up it `.dependency-cruiser.js` now. 
Tricks that I used:
- I don't have webpack, but I should have a webpack.config file only for your config, so I made fake webpack file with 'resolve' configuration
- I have complex rules that is not easy to describe by regexp manually, so I generate regexp programmatically to fit dependency-cruiser
I would be happy to put resolve config from webpack directly to `.dependency-cruiser.js` and have ability to define rules as
```ts
  {
    name: 'my dynamic rule',
    comment: '',
    severity: 'error',
    from: {
      path: (arg) => (..) ? true : false,
    },
    to: {
      pathNot: (arg) => (..) ? true : false,
    },
  }
```

**Comment by sverweij** [comment]
hi @tvolodimir - thanks for the numbers and the configuration 60s is still too much for 500 modules (especially for typescript) - I see the same on the CI, though - on windows the _forbidden dependency check_ step takes [51s](https://github.com/sverweij/dependency-cruiser/runs/1339124125?check_suite_focus=true)(!) - on linux it only takes [9s](https://github.com/sverweij/dependency-cruiser/runs/1339124144?check_suite_focus=true). Similar numbers for the test suite. Not sure on it's 100% apples to apples, but while other steps take longer too, it's not typically 5x. 

As the _start of node process_ on your machine also takes 3s (typical: ~700ms) I expect windows-specific shenanigans. I wiped the dust of my corporate windows laptop and will do some poking around in the coming days. In initial tests it's indeed slow as a snail there (i5, windows 

> It's a bit complicated to set up it .dependency-cruiser.js now.

The config possibilities have grown a bit more than I like too. Dependency-cruiser tries to hide as much of the complexity as possible, but can't hide everything due to the diversity of possibilities in the (java|type)script ecosystem. And there's some backward compatibility kerfuffle that makes some of the options unintuitive (e.g. tsPreCompilationDeps). 

It's one of the reasons dependency-cruiser has a `--init` that takes care of a decent first set up. It's the reason also I'm playing to _guess the right things_ on runs without a config, but that's a Christmas holiday sized kind of job...

> - I don't have webpack, but I should have a webpack.config file only for your config, so I made fake webpack file with 'resolve' configuration.

It shouldn't be necessary to provide a webpack config in your situation. Dependency-cruiser internally takes care of everything that is in `fake-webpack.config.js`- handling symlinks, passing extensions and configuring the ts-config-paths plugin when relevant. It's happening in [resolve-options/normalize.js](https://github.com/sverweij/dependency-cruiser/blob/1b53650100ddf48e63d6d192883b9ec301bf7d85/src/main/resolve-options/normalize.js#L67)). 

> - I have complex rules that is not easy to describe by regexp manually, so I generate regexp programmatically to fit dependency-cruiser

If you're at liberty to share them: consider me _extremely_ interested in those rules!

**Comment by tvolodimir** [comment]
> It shouldn't be necessary to provide a webpack config in your situation. 

not in my situation, as I have shown before, without webpack config I have a dramatically bad situation with 'resolve' step

> If you're at liberty to share them: consider me extremely interested in those rules!

I have custom _module_ abstraction, And dozen of these _modules_ in one node package.
And I strictly define dependencies between these _modules_ in one json
```ts
// simplified example

// 'pure' means not core and exotic dependencies
const modules = {
  core: {
    dir: 'src/modules/core',
    main: './public_api.ts',
    pure: true, deps: []
  },
  'core.inv.ui': {
    dir: '../core-ui/dist',
    main: './index.js',
    pure: true, deps: ['core']
  },
  'core.env-browser': {
    dir: 'src/modules/core.env-browser',
    main: './public_api.ts',
    deps: ['core', 'core.inv.ui']
  },
  'core.env-electron': {
    dir: 'src/modules/core.env-electron',
    main: './public_api.ts',
    deps: ['core', 'core.inv.ui', 'core.env-browser']
  },
  'foundation.inv': {
    dir: 'src/modules/foundation.inv',
    main: './public_api.ts',
    pure: true, deps: ['core', 'core.inv.ui']
  },
};
```
for this structure with N modules is not very easy to set up O(N^2) rules 🤨

**Comment by curledUpSheep** [comment]
I'm facing a similar performance issue (dependency-cruiser 9.21.0, Windows 10, SSD):

```
156840ms     150Mb     125Mb reading files
...
× 2 dependency violations (0 errors, 2 warnings). 1153 modules, 3803 dependencies cruised.

      2ms     152Mb     123Mb really done (157891ms)
```

I'm running depcruise on a Lerna monorepo with quite some symlinks to internal packages in the monorepo, sometimes nested.

In my case, it seems the issue is the `gatherScannableFilesFromDirectory` function in `gather-initial-sources.js`. This recursively builds a huge list of files, only performing filtering when it gets down to the level of actual files. This means that, if I set a `doNotFollow` for `node_modules`, it will still go into the node_modules folder and list all files as deep as it can.

For our particular repo, this leads to `gatherScannableFilesFromDirectory` being called a huge number of times with paths like `api\node_modules\@company\internal-symlinked-package-A\node_modules\@company\internal-symlinked-package-B\node_modules\@company\internal-symlinked-package-C\node_modules\@babel\helper-member-expression-to-functions\node_modules\lodash\fp` (even though all of these files will be excluded from the result because we have a `doNotFollow` for `node_modules`).

As a test, I added the following code at the start of `gatherScannableFilesFromDirectory`'s `.reduce()` callback:

```
if (!keepNonExcluded(pathToPosix(path.join(pDirectoryName, pFileName)), pOptions)) {
  return pSum;
}
```

This results in a >10x performance improvement on our repo (from 2.5 minutes to 15 seconds):

```
13696ms     148Mb     122Mb reading files
...
× 3 dependency violations (1 errors, 2 warnings). 1153 modules, 3799 dependencies cruised.

      5ms     151Mb     120Mb really done (14756ms)
```

For our use case, this doesn't seem to affect any of the rule checking (it looks like `gatherScannableFilesFromDirectory` would filter out these files anyway). However, I can imagine that this breaks behavior for people using `doNotFollow`, `includeOnly` or `exclude` with expressions that are intended to be checked only against the full file path.

Still, I think it's a very common use case to have a `doNotFollow` with a `path` array only containing simple strings like `node_modules`, `coverage`, `test-reports` etc. where it's safe to exclude matching directories without going any deeper. If we could detect those cases and apply the filtering as early as possible, it could result in quite a big performance gain.

@sverweij do you think it would make sense to set up something like this? If you don't have the bandwidth to implement it, I might be able to free up some time to create a PR.
