### ISSUE TITLE
Not a bug or a feature: How to resolve special webpack prefixes at import path

### ISSUE THREAD

**Issue by tvolodimir** [sverweij/dependency-cruiser#388]
Hot to handle impots like 
`import 'style-loader!./canvas.css';`
`import htmlContent from 'raw-loader!@my-module/dist/index.html';`

### Summary

In webpack work, exists inline loaders ( https://webpack.js.org/concepts/loaders/#inline )
I am wondering, if there exist way to handle it in `dependency-cruiser`

**Comment by sverweij** [comment]
Hi again @tvolodimir at the moment there's no support for them, simply because nobody asked for it. Until now :-). From the examples it seems the file name to look for is always after the last `!` in the import statement, so simply resolving that one might do the job. Anyway - I'll put it on the backlog.

That said - I read webpack [recommends](https://webpack.js.org/concepts/loaders/#using-loaders) to pass them in the webpack config's `module.rules` (indeed looks a bit cleaner). Are there reasons to use inline loaders in stead?

**Comment by tvolodimir** [comment]
> Are there reasons to use inline loaders in stead?

In general, I don't use inline prefixes, but in some cases, it's necessary. to explicitly show your intent what do want to do with dependencies
```ts
import ./canvas.css'; // injects styles to head of html
import htmlContent from 'raw-loader!./canvas.css'; // get content without any injections or pasring css
```

> From the examples it seems the file name to look for is always after the last ! in the import statement, so simply resolving that one might do the job
It will be very helpful if `dependency-cruiser` will support hook for this
```ts
{
  options: {
   preResolveProcessingHook: (url) => {
     const i = url.lastIndexOf('!');
     return i >-1 ? url.substr(i + 1) : url;
  }
}
```

**Comment by sverweij** [comment]
Hi @tvolodimir there'll be a PR to properly support inline loaders (and the similar concept from require.js) real soon. As it was possible to do this configuration free against no noticeable performance impact and 100% non-regression I've chose to go that route. When the PR drops I'll publish a beta to npm as well so you can see if it works for your use case(s) - details will follow.

**Comment by sverweij** [comment]
Published on npm as `dependency-cruiser@9.17.0-beta-1` - I'd love to hear your feedback!

**Comment by tvolodimir** [comment]
works well, thanks a lot

**Comment by sverweij** [comment]
It's now part of the regular release as well (9.17.0) - thanks for the request & the quick validation!
