### ISSUE TITLE
Issue: Files suffixes are not matched with import without file suffix

### ISSUE THREAD

**Issue by lwolle** [sverweij/dependency-cruiser#422]
There appears to be a regression between versions `9.21.4`and `9.21.5`. The generated diagrams differ by the fact, that the files are not matched with the import statements if those are written without file endings in version `9.21.5` and `9.21.6`.

### Expected Behavior
Imports can be written without explicit file ending, and dependcy-cruiser resolve those imports to the _correct_ file on disk, e.g. `import { Home } from src/modules/Home/Home`

Example from `9.21.4`
![9-21-4](https://user-images.githubusercontent.com/20285765/104845016-8bb26480-58d3-11eb-868c-c8a9f2dd4539.png)

### Current Behavior
Imports need to have explicit file endings, otherwise the file and the import statement can not be matched and two nodes appear for the same file in the graph.

example 
`import { Home } from src/modules/Home/Home`
![9-21-5](https://user-images.githubusercontent.com/20285765/104845038-a71d6f80-58d3-11eb-959f-782680621e20.png)

`import { Home } from src/modules/Home/Home.ts`
![9-21-5_with_suffix](https://user-images.githubusercontent.com/20285765/104845111-08454300-58d4-11eb-85c4-022ac039e674.png)

Even though adding file suffix seems to "repair" the issue visually, the imported locations appear to be resolved differently, as they show a red font color and border color. No custom node-type dependent coloring is specified.

### Steps to Reproduce (for bugs)

1. `git checkout https://github.com/lwolle/dep-cruise-babel-config-error.git`
2. `git checkout ts-file-suffix-problems`
3. `yarn install`
4. `yarn cruise`

### Context
The project is commercial and i can't share a link to it and the sources unfortunately. I'm wondering if the issue is related to our custom setup that uses absolute imports, because changing the import statements to relative imports solves the problem. Are absolute imports supported at all?

### Your Environment

- Version used: 9.21.5
- Node version: 12.14.14
- TypeScript version: 4.1.3
- Operating System and version: macOS 10.15.1
- Link to your project: [https://github.com/lwolle/dep-cruise-babel-config-error](https://github.com/lwolle/dep-cruise-babel-config-error)

**Comment by sverweij** [comment]
Hi @lwolle - thanks for raising this issue too, and again thanks for going through the lengths to create a minimal reproduction repo. (It does seem the [dep-cruise-babel-config-error](https://github.com/lwolle/dep-cruise-babel-config-error.git) repo on GitHub does not have a ts-file-suffix-problems yet - maybe it still needs to be pushed from local?) Nevertheless - while poking at another problem I seem to have found a possible cause:
- in 9.21.14 dependency-cruiser loaded a plugin (ts-config-paths) when there was a tsconfig.json with af baseUrl in it. In 9.21.15 it additionally checks for the existenc of `paths` in the tsconfig. Why? loading tsconfig-paths takes startup time and the plugin slows down file resolution even when there's no `paths` extra to resolve (~1ms per resolve, which tends to add up on serious monorepos).
- TIL: It seems ts-config-paths plugin has a side effect where it attempts an extra resolve for 'src/yadda' to `baseUrl + 'src/yadda'`- which happens to be exactly what you expect in this issue. 

(I was only able to replay this with the typescript compiler (which gets put into action when `tsPreCompilationDeps: true` or when there's no babel in the neighbourhood) and not yet with babel only but I'm quite confident it's the root cause in any case as it's the only significant change in 9.21.5).

> Just an aside out of curiosity: what's the reason to use babel's typescript config (/ plugins) over the real typescript compiler?

**Comment by lwolle** [comment]
Hey @sverweij, yeah true. Missed to push the changes for the case. So the only change is that in this case the babel option is not used, and I rely on ts only. As you've said, that's exactly my case because in the setup of the current issue, I did not provide a babel config. I stumpled upon the reported issues while trying to get our setup to run, and could not wrap my head around it.

To answer the side question: There's currently no way around babel in the js world, right? And to make things easier to reason, and presumably faster to (re-)compile (even though there seems to be evidence pro and counter this argument), we decided to remove ts compilation from the build step, and consequently from webpack as well. So the build config is dead simple, and there are no other language loaders in webpack besides the babel-loader. I enjoyed that setup a lot, and feel to have less issues with the build-step than in previous projects. Maybe just a matter of tase 🙂.

Thank you for getting to the issues so quickly. I appreciate it!

**Comment by sverweij** [comment]
Hi @lwolle I've rolled back the PR I suspected to be the root cause of this issue, published it as a `dependency-cruiser@9.21.7-beta-1` and ran it against the branch in your repro repo - and it seems it indeed solves this issue.

=> could you confirm?

**Comment by sverweij** [comment]
The PR is merged and the fix is now also part of the (freshly published) `dependency-cruiser@9.21.7`
