### ISSUE TITLE
Highlight svg path when clicked so that it is easy to follow through dense thickets of paths

### ISSUE THREAD

**Issue by ulfakerlind** [sverweij/dependency-cruiser#434]
As a freelancer I am trying to wrap my head around existing projects everyday. Sometimes the dependency graphs are so dense and cluttered that I cant get anything from them. 
### Expected Behavior

When I click or hover anywhere on an svg path, the line can change color. Preferably with a click

### Possible Solution
Embedd css straight into the .svg file
or
Somehow embedd css plus javascript so that you can click, and if you click the next line, the former line goes back to its original color

### Considered alternatives

Adding the extra xml and css manually to get the desired behavior
Running depcruise in the particular folder I am interested in works great for the time being. But this is time consuming

**Comment by sverweij** [comment]
Hi @ulfakerlind do you mean something [like this](https://sverweij.github.io/dependency-cruiser/assets/react-high-level-dependencies.html)? That should already be possible with the tiny [depcruise-wrap-stream-in-html](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#depcruise-wrap-stream-in-html) utility that ships with dependency-cruiser - would that help? (Suggestions for) improvement welcome!

> Dependency-cruiser only generates a .dot output. GraphViz dot takes care of transforming it to svg, so that's why 
> it's not in the main script. `depcruise-wrap-stream-in-html` just wraps the svg in html and adds css + javascript to
> make it interactive.

B.t.w. some things I've found useful when spelunking new code bases:

- Pipe the output of the command to the [`browser`](https://gist.github.com/defunkt/318247) script instead of redirecting it to a file, so it instantly shows up on your screen.
- It's possible to have dependency-cruiser add [prefixes to links](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#prefix-prefix-links-in-reports). Not only useful to open modules froma central git repo, but also to open in your local editor.
- When the graph is not too big hinting GraphViz to use orthoganal lines for spline routing typically improves readability quite a lot (command line `... | dot -Gsplines=ortho -T svg | ...` - or configure it in [.dependency-cruiser.js](https://github.com/sverweij/state-machine-cat/blob/v7.3.0/config/dependency-cruiser-graph.js#L13) (if the graph is too big/ complex GraphViz will take either forever or eek out - so ymmv with this one).

See e.g. [this script in dependency-cruiser's package.json](https://github.com/sverweij/dependency-cruiser/blob/v9.22.0/package.json#L73) or a similar one in [state-machine-cat's package.json](https://github.com/sverweij/state-machine-cat/blob/v7.3.0/package.json#L20) that combine these tricks

**Comment by ulfakerlind** [comment]
Awesome! will try it out!

**Comment by ryanfitzer** [comment]
Hovering over a module node works great (route lines change color), but when the graph is larger than the viewport, tracking the route lines that go above/below the fold is not possible, since you mouse needs to exit the module node to scroll the browser to see the route path. Some way to toggle the route line color would be a nice feature.
