### ISSUE TITLE
Support request: Trying to understand the orphan rule

### ISSUE THREAD

**Issue by jzaefferer** [sverweij/dependency-cruiser#448]
The other day I noticed this unused React hook in our project:
```
import { useRef, useEffect } from 'react'

export default function usePrevious<T extends any>(value: T): T {
  const ref = useRef<T>(value)

  useEffect(() => {
    ref.current = value
  }, [value])

  return ref.current
}
```
This was not flagged as an orphan by our no-orphan rule:
```
    {
      name: 'no-orphans',
      severity: 'warn',
      from: {
        orphan: true,
        pathNot: [
          '(^|/)\\.[^/]+\\.(js|cjs|mjs|ts|json)$', // dot files
          '\\.d\\.ts$', // TypeScript declaration files
          '(^|/)tsconfig\\.json$', // TypeScript config
          '(^|/)(babel|webpack)\\.config\\.(js|cjs|mjs|ts|json)$', // other configs
        ],
      },
      to: {},
    },
```
I've ready the docs for the `orphan` setting, which say:
> A Boolean indicating whether or not to match modules that have no incoming or outgoing dependencies.

I get the incoming dependencies, but not the outgoing ones. In my case, if I remove the React imports, the module gets flagged as an orphan, but that's not useful for me to find unused code.

Is this the intended behavior or the orphan rule? If so, is there some (other) way to flag my example hook as unused?

### Environment

- Version used: 9.22.0
- Node version: v14.15.0
- Operating System and version: OSX 10.15.7

**Comment by sverweij** [comment]
hello @jzaefferer - thanks for reaching out. 

The module is indeed not flagged as an orphan because it still depends on an external module (`react`). It is possible to find and flag these modules in a few ways.

### use [_reachable_](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#reachable---detecting-dead-wood-and-transient-dependencies)
When the module(s) in question are problematic because they aren't reached from (i.e.) the root module, a rule like this in the forbidden section should then root them out:

```javascript
{
  name: "not-reachable-from-root",
  from: {
   path:  "^src/index.ts",
  }
  to: {
    path: "^src",
    pathNot:  "^src/index.ts",
    reachable: false
  }
}
```
Group matching will work with _reachable_ rules as well, so if all modules within a feature should be reachable from the root of that feature, something like this in the forbidden section should get you set:
```javascript
{
  name: "not-reachable-from-feature-root",
  from: {
   path:  "^src/features/([^/]+)/index\.ts",
  }
  to: {
    path: "^src/features/$1/",
    pathNot: "^src/features/$1/index\.ts",
    reachable: false
  }
}
```

### use the dependents check
From the next version (currently released as `dependency-cruiser@9.24.0-beta-1` - likely out of beta by this weekend) it's also possible to use the number of dependents of a module in a rule. I.e. this rule in the _forbidden_ section will root out every module in the _src_ folder that is used by 0 other modules in _src_:

```javascript
{
  name: "no-internal-orphans",
  from: {
    path: "^src/"
  },
  to: {
    path: "^src/",
    numberOfDependentsLessThan: 1 
  }
}
```
> There will be a [recipe](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-tutorial.md#recipes) for this in the rules tutorial in addition to the rules documentation as per your previous suggestion :-)


### ignore all external modules
In its configuration you can filter what dependency-cruiser scans. E.g. with _exclude_ you can pass 'node_modules' to exclude external modules, or with _includeOnly_ you can pass "^src/" to ensure only modules within _src_ get scanned (this last one might be better if you also want to exclude node native modules like _fs_ or _path_).

This approach is not suitable if you have any rules that _do_ put restrictions on dependencies on external modules, though.



> I notice the line in the documentation quoted above should be cleaned up so it reads a bit more unambiguously as `NOT incoming AND NOT outgoing` instead of `NOT(incoming OR outgoing)`
>> A Boolean indicating whether or not to match modules that have no incoming ~~or~~ *and no* outgoing dependencies.

**Comment by jzaefferer** [comment]
Thanks a lot! I've tried out the reachable option and ended up with this solution. We found about 750 more dead lines of code :D 

```
{
  name: 'not-reachable-from-root',
  comment:
    "This is another kind of orphan - it has dependencies, but isn't imported from anywhere we care about. Either remove it or use it. Exceptions: test and story files and assets; and currently the LanguageSwitch component.",
  severity: 'error',
  from: {
    path: '^src/index.js',
  },
  to: {
    path: '^src',
    pathNot: [
      '^src/index.js',
      '^src/__mocks__/axios.js',
      'test.(t|j)sx?',
      'stories.(t|j)sx',
      '^src/mocks',
      '^src/fixtures',
      '^src/utils/test-utils',
      '^src/setupTests.js',
      '.d.ts',
      '^src/assets/tunes_thumbnails',
      '^src/components/LanguageSwitch',
    ],
    reachable: false,
  },
}
```

Once `numberOfDependentsLessThan` is out of beta, I'll try that, too. Hopefully it'll need less of these exceptions.

**Comment by sverweij** [comment]
hi @jzaefferer thanks for the feedback - and I'm happy to see it works!

The [`numberOfDependentsLessThan`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#rules-on-dependents---numberOfDependentsLessThan) went out of beta with yesterday's 9.24.0 release. This release also  contains the documentation fix + [two _recipes_](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-tutorial.md#is-a-utility-module-shared), one of which directly inspired by this issue.

**Comment by danielo515** [comment]
Sorry for commenting on a closed thread, but I don't see how I can build a rule that warns me about files that are not required by any other module.
 Seems that numberOfDependentsLessThan may be the thing I'm looking for, but it is always targeted at some from folder. What if I want to find files that are not used by anybody no matter what libraries they import?

**Comment by sverweij** [comment]
hi @danielo515 don't worry about reaching out - it helps me understand what struggles people have when using the tool. Typically it might lead to improved documentation and sometimes even improvements in the tool itself. Next time don't hesitate to create a separate issue, though - closed issues can be easier to miss for me than others.

About your question: If you're looking for modules that aren't used by any other modules (but might themselves use others) a rule with the [reachable]() attribute might be what you'r looking for. The example in that piece of documentation uses it to detect dead wood from the perspective of a single entry point (which might be what you want), but it's also possible to use it more generally. E.g. 

```javascript
  {
    "name": "no-modules-unreachable-from-anywhere",
    "severity": "error",
    "from": {
      // from part left empty on purpose
    },
    "to": { 
      "reachable": false 
    }
  },
```

Will match _any_ module that don't have incoming dependencies (/ = aren't required or imported by any other module). This example is _very_ generic, though - and it will also flag spec files. In the example in the linked documentation you can see how to fix that.

Hope this helps. If this doesn't match your use case please let me know!

**Comment by danielo515** [comment]
Hello @sverweij , thanks for your super quick answer, and sorry for commenting in an old issue. Next time I will create a new issue.
To be completely honest with you, I didn't properly read the docs. I was looking for a quick way to plot my dependencies and this tool was the first one I found. After some minutes I realised that my deps were to messy to efficiently plot them, but luckily this tool was much more than just plotting and I started using it as advertised. However, I was in kind of a hurry and I just read the docs diagonally looking for what I thought I needed. I remember that I was not able to fully understand even some sentences that made perfect sense just because how fast I was trying to read them.
I promise that I will read the docs more carefully and give a better opinion about them.

The reachable option looks like the perfect fit for my use case for several reasons. The first is that my application is a web app, and the only entry point is index.tsx. Second, because there are several modules that are not used on the application but are still required by their unit tests. I was struggling to find unused modules using `numberOfDependentsLessThan` because they had tests. Increasing the amount of minimum dependents to 2 was not an option because there are many used modules without tests.
So yea, looks that reachable is the prefect candidate. At first I was not sure if it traverses the entire tree and that's why I didn't considered using it, but seems that It will analyse the complete tree to check if something is used or not. I will give it a try.

This is an awesome project that really allows to do efficient analysis and enforce practices that are impossible to enforce without it. I think I will start using it on all my projects and recommend it  to everyone.

Thanks and regards
