### ISSUE TITLE
Not a bug or a feature: detect unused npm packages

### ISSUE THREAD

**Issue by gordonmleigh** [sverweij/dependency-cruiser#468]
Thanks for a cool tool. I couldn't find any info on this after a long search – is it possible to detect which of the packages in package.json are not used in the project?

**Comment by sverweij** [comment]
Hi @gordonmleigh - thanks for the compliment.

In theory it _is_ possible to detect unused dependencies in package.json - with some manual work, but it's not built-in functionality at the moment. I haven't made it a priority, because packages like  [dylang/npm-check](https://github.com/dylang/npm-check) or [depcheck](https://github.com/depcheck/depcheck) already have this in their core functionality and - in my experience - already do that quite well.

**Comment by gordonmleigh** [comment]
No worries, thanks.
