### ISSUE TITLE
Feature request: Rebase old errors

### ISSUE THREAD

**Issue by binary64** [sverweij/dependency-cruiser#493]
### Context

I currently have 847 something violations. It's going to be a chore to get these fixed in our codebase. However, if I could run something like a `depcruiser --rebase` flag, then it could write all the current errors to a file starting with `.` that we would commit to git. Then, if your tool encounters the exact same error, it can downgrade it to a warning/info/hidden.

### Expected Behavior

`depcruise **/*` - shows a load of errors, exit code >0
`depcruise --rebase **/*` - shows a load of errors, exit code 0
`depcruise **/*` - shows 0 errors, exit code 0
(make some changes to code to introduce a new error)
`depcruise **/*` - shows 1 error, exit code >0
`rm .dependency-cruiser.json ; depcruise **/*` - shows loads of errors again, exit code >0

### Possible Solution

The dot file format could be an array of strings like
```
error not-to-dev-dep: libs/ui/.storybook/preview.js → node_modules/@storybook/react/dist/cjs/client/index.js
```
would be one element of the array.

**Comment by sverweij** [comment]
Hmm - generating a baseline and working from there. That's an interesting approach to this problem @binary64. Might beat the manual approach I've used so far. I like it. The `.` file (`.dependency-cruiser-known-violations.json` I guess) would be trivial to generate, using it in or just before the reporting step shouldn't be to hard either. I'll see if I can whip up a little PoC in the coming days.

**Comment by sverweij** [comment]
hi @binary64 I've hammered out a crude(but working) prototype and released it as `dependency-cruiser@10.3.0-beta-3`. There's some ergonomics that need fixing and I'd love to hear feedback.

- the `err` reporter currently still displays the known error, albeit with a lowered severity (ignore) - should it display them at all? I lean to not showing them at all because we already decided they're known errors we'll handle at a later moment, and even showing them as 'ignore' (or 'known') generates visual noise - especially when there's hundreds of them. What's your thoughts about this?
- in the beta dependency-cruiser blindly takes them into account. If I'd want to review know violations, I'd have to remove the baseline file. It might be more convenient to have a command line switch to steer this behaviour. E.g. to ignore known violations you'd have to pass a `--ignore-known-violations` switch (optionally taking a filename with the known violations?). Not passing that switch would then show both known and new violations as they were before. Your thoughts?


(I did test the baselining feature against dependency-cruiser itself).

### baselining known violations with `dependency-cruiser@10.3.0-beta-3`
After you've installed it generate the baseline with the `baseline` reporter e.g.:

```sh
depcruise src \
  --config .dependency-cruiser.js \
  --output-type baseline \
  --output-to .dependency-cruiser-known-violations.json
```

You can e.g. put that in a `depcruise:baseline` script in package.json.

After `.dependency-cruiser-known-violations.json` is created, dependency-cruiser will filter all known errors and lower their severity to 'ignore'.

Sample output _without_ the known violations in place:

```
 ~/prg/js/dependency-cruiser$ yarn depcruise
yarn run v1.22.11
$ node ./bin/dependency-cruise.js src bin test configs types tools --config --progress

  info utl-module-not-shared-enough: src/utl/wrap-and-indent.js
  info utl-module-not-shared-enough: src/utl/array-util.js
  info not-reachable-from-folder-index: src/cli/validate-node-environment.js
  info not-reachable-from-folder-index: src/cli/tools/wrap-stream-in-html.js
  info not-reachable-from-folder-index: src/cli/format.js
  error not-unreachable-from-cli: src/schema/baseline-violations.schema.js

✖ 6 dependency violations (1 errors, 0 warnings). 439 modules, 1074 dependencies cruised.

error Command failed with exit code 1.
```

Sample output with the known violations in place:

```sh
 ~/prg/js/dependency-cruiser$ yarn depcruise
yarn run v1.22.11
$ node ./bin/dependency-cruise.js src bin test configs types tools --config --progress

  ignore utl-module-not-shared-enough: src/utl/wrap-and-indent.js
  ignore utl-module-not-shared-enough: src/utl/array-util.js
  ignore not-unreachable-from-cli: src/schema/baseline-violations.schema.js
  ignore not-reachable-from-folder-index: src/cli/validate-node-environment.js
  ignore not-reachable-from-folder-index: src/cli/tools/wrap-stream-in-html.js
  ignore not-reachable-from-folder-index: src/cli/format.js

✖ 0 dependency violations (0 errors, 0 warnings). 439 modules, 1074 dependencies cruised.
```

**Comment by sverweij** [comment]
Hi @binary64 (ping?)

I've been using the above-mentioned version a few days and ...
- having ignored errors show up in the error output (even when grayed out and with 'ignore' in front of them) is not very ergonomic. For now I've removed ignored errors from the output. Later on dependency-cruiser might grow (yet another...) option to specify the 'softening' level to be something different from 'ignore' (i.e. 'info' or 'warn').
- Having a switch to show and hide known violations is indispensable. The switch is currently called `--ignore-known`. It takes an optional filename (which defaults to .dependency-cruiser-known-violations.json) so you can put it on an alternative spot (or even use different ones on different runs).


I currently use these two scripts in dependency-cruiser's own package.json (abbreviated for clarity):
```javascript

    // create the known-violations
    "depcruise:baseline": "depcruise src bin test configs types tools --config --output-type baseline --progress --output-to .dependency-cruiser-known-violations.json",
    
    // reads known violations from .dependency-cruiser-known-violations.json and ignores them
    "depcruise": "depcruise src bin test configs types tools --config --ignore-known",

    // doesn't know about known violations so shows them all
    "depcruise:all": "depcruise src bin test configs types tools --config",
```

You can try the same with `dependency-cruiser@10.3.0-beta-4` - which was just published to npm. Feedback welcome!

**Comment by binary64** [comment]
Hi. Thanks for the betas, I have just tried beta-4 with `depcruise libs apps --config --ignore-known` and I see

```
√ no dependency violations found (6143 modules, 13357 dependencies cruised)

Done in 119.46s.
```

This isn't strictly true - dep violations were found - except we're ignoring them. So under that green tick, it would be great to see an orange triangle icon with something like "1,505 knonw violations are currently being silenced"

I also have some feedback about the command line args, they could be a bit more terse.  --output-type might want nothing to do with the known json - maybe someone wants both to get output.

Thank you for this, I can't wait to install it into my CI and see when I get the first "new" violation come in.

**Comment by sverweij** [comment]
@binary64 thanks for the feedback. 

> This isn't strictly true - dep violations were found - except we're ignoring them. So under that green tick, it would be great to see an orange triangle icon with something like "1,505 knonw violations are currently being silenced"

I agree. In other reporters where violations play a central role (e.g. err-html, html, teamcity) we'll have to do something similar.

> I also have some feedback about the command line args, they could be a bit more terse. --output-type might want nothing to do with the known json - maybe someone wants both to get output.

There's the `-T` variant of `--output-type`, which would make the command line shorter, but I have the feeling you mean something else (check?). If so, cannyou give an example?

**Comment by binary64** [comment]
I don't mean the short version like `-T` I mean instead of `--output-type baseline --output-to .dependency-cruiser-known-violations.json` which is very long and hard to memorize, how about `depcruise apps libs --generate-baseline`

But also allow `--generate-baseline` in conjuction with `-T json`

**Comment by sverweij** [comment]
Hi @binary64 - was afraid of that :-) 

On the one hand the baseline command is probably going into a script anyway, on the other hand the current invocation is indeed a bit much for something conceptually simple. I've whipped up command that should ease this. When you use the defaults a `depcruise-baseline libs apps` should suffice; cli doc:

```
Usage: depcruise-baseline [options] <files-or-directories>

Writes all violations of rules in a .dependency-cruiser.js to a file.
Alias for depcruise -c -T baseline -f .dependency-cruiser-known-violations.json [files-or-directories]
Details: https://github.com/sverweij/dependency-cruiser

Options:
  -c, --config [file]     read rules and options from [file] (default: true)
  -f, --output-to [file]  file to write output to; - for stdout (default: ".dependency-cruiser-known-violations.json")
  -V, --version           output the version number
  -h, --help              display help for command
```

I've added it and published it as the next beta (`dependency-cruiser@10.3.0-beta-6`). 

- Adding it as (yet) another command line option to `depcruise` is possible but I currently don't see a clean (maintainable) way to do so (this might be because of the late hour, though).
- I have a hard time to conceptually grok generating known-violations while at the same time checking for these same violations - but again, it's late so I might miss something. Can you help me understand in what scenario this would be useful?
