### ISSUE TITLE
Feature request: Vue SFC + preCompilationOnly

### ISSUE THREAD

**Issue by rklos** [sverweij/dependency-cruiser#515]
There is any chance to implement `preCompilationOnly` option for Vue SFC with TypeScript support?

### Context
I want to set rules with `preCompilationOnly` for my whole Vue.js + TypeScript project without being limited to `.ts` files.

### Expected Behavior

`preCompilationOnly` will include `.vue` files with TypeScript support

### Current Behavior

`preCompilationOnly` option doesn't work for Vue SFC even if it has Typescript support (via `<script lang="ts">`)

**Comment by sverweij** [comment]
Hi @rklos it's possible to implement this. We'd have to 

1. make the vue pipeline aware of the types of their scripts (dependency-cruiser currently assumes javascript - typescript happens to work due to its similarity to javascript and due to the flexibility of the acorn compiler we use).
2. modify the vue pipeline to do the pre/post compilation comparison

Currently the pipeline for vue sfc's looks like this:

vue sfc -> javascript -> (js) AST -> post compilation dependencies

to get preCompilationOnly attributes we'd have to modify this to 

vue sfc -> typescript -> (ts) AST -> both pre and post compilation dependencies

and

vue sfc -> typescript -> javascript -> (js) AST -> post compilation dependencies only

and compare the outputs.

This looks simple, but it'll likely be a moderately complex change because dependency-cruiser's pipelines are set up in a more-or-less generic fashion to support an array of compiles-to-javascript languages (a.o. vue sfc's, svelte, babel).
