### ISSUE TITLE
How to use regex with multiple source paths?

### ISSUE THREAD

**Issue by edaqa-uncountable** [sverweij/dependency-cruiser#525]
### Summary

I want to write a rule that looks like below, where I have multiple source paths with pathNot, but have some exclusions to make.

```
    {
      name: "app-family",
      severity: "error",
      from: {
        pathNot: [
          "^site/js/([one|two])",
          "^site/js/but_not_this_one.tsx",
        ],
      },
      to: { path: ["^site/js/$1"] },
    },
```

I want the regex to match only the first listed item in the array.

### Context

I'm trying to say that all other modules in our app are not allowed to import from `one` or `two`, except those modules themselves.  This list will get a lot longer. It's an attempt to keep the modules isolated -- at a high-level in the import hierarchy.

There is however an exception, the `but_not_this_one.tsx` file is allowed to import from those folders. In our case this is the top-level react router app that references each of the individual apps. It's this need for an exception that looks like it's preventing the regex replacements to work -- the above rule ends up doing nothing (no violations at all, despite some without the regex).

### Environment

"dependency-cruiser": "10.0.1",

**Comment by sverweij** [comment]
hi @edaqa-uncountable it looks like the idea you have is correct, but the regex syntax isn't entirely. The capturing group (the stuff between `(` and `)` is in the right spot, but if I'm not wrong `[one|two]` means _match a single character as long as it matches any of the ones within the square brackets_ - so that part of the regex matches files like `site/js/o` `site/js/|` etc. Removing the square brackets will probably be closer to what you want: ` "^site/js/(one|two)"`.

When a regex doesn't work I typically use an online tool (like [RegExr](https://regexr.com) - but any search engine will cough up dozens of them) and test out what happens against a few example string. The only thing in those tools is that forward slashes (`/`) must be escaped (with a backslash: `\/`) whereas that is not mandatory in the regexes used in dependency-cruiser rules.
