### ISSUE TITLE
Struggling with the docs...

### ISSUE THREAD

**Issue by larruda** [sverweij/dependency-cruiser#550]
Hi. Sorry for opening this, but I really spent a few hours on the docs and trying out a bunch of different options but none so far got me the results I need. 

My goal is simple (I suppose). I have a large monorepo project which I need to analyze the dependencies between modules. I'd like to see every (max depth) module/folder (no source file) only in the report. So far what I've got  is either a very consolidated report with the root module's only (archi) which doesn't satisfy, or a very polluted report with every single file on it. In fact the closest I got was using `--collapse` with a number but as modules have different depths from each other some still get too collapsed at the end. 

I hope I was clear enough. This tool (or its docs) seems like a little (unnecessarily?) complex to understand, although I appreciate having it there. Thanks!

**Comment by sverweij** [comment]
Hi @larruda - creating a usable graphs for large repos is a bit of a challenge regardless of the tool you use. I probably need to create a tutorial for it - this issue made me aware of that once again, so thanks!

 I've tried to keep the use of the tool as simple as possible and reduce/ hide as much of the complexity as I could (e.g. with sane defaults, a --init for scaffolding a config larded with comments, being conservative with taking on new features). At the same time it's still possible to configure most of dependency-cruiser's behaviour when it's really necessary. That's also what the documentation currently reflects. Looking at it right now I can see it seems a bit overwhelming. I think some tutorials for major use cases (rules set up for small and large repos, tweaking visualisation) might help tame that - but if you have other suggestions I'm open to them...

I've shared some things I've found helpful in the past to visualize large-ish mono repos with dependency-cruiser below. However, it might be that the challenges you face are more specific to your current setup. If so feel free to share a bit more details, and I'll see whether I can help out with that.

HTH

- There's a reporter that only takes only folders into account (`ddot`). Probably the easiest as it takes hardly any configuration - [here's](https://sverweij.github.io/dependency-cruiser/dependency-cruiser-dir-graph.html) how that looks for dependency-cruiser itself. Passing `ddot` instead of `dot` to --output-type will do the trick:
```shell
depcruise bin src --config .dependency-cruiser.js --output-type ddot | dot -T svg > dir-graph.html
```
- passing a regex to --collapse (or, maybe easier: to the `archi.collapsePattern` option in your _.dependency-cruiser.js_) that is targeted to your mono-repo might help you show the desired folders. I once encountered a mono-repo that was migrating from lerna-based to a nx-like setup. The lerna based setup had business components in `packages/bc-{name}`. As each of them was developed by a different (geo-distributed) team what happened below differed a bit. Some teams had a `lib` folder, some a `src` and others had their source code under `src/lib` 1). I ended up cooking a collapsePattern that took all of these into account. I've included a simplified version below
- For when you're not using regular expressions on a day-to-day basis: `[^/]+` ('one or more characters not being a `/`) matches a folder.
- If interesting stuff for one of the styles of folder happened a bit deeper down, I'd just add an extra `[^/]+` at the end of a pattern.
- Instead of an array of patterns it's also possible to pass one big-ass regex - which would also be usable on the command line. It might prove to be not super readable though (`^packages/bc-[^/]+/src/lib[^/]+|^packages/bc-[^/]+/lib[^/]+|^packages/bc-[^/]+/src[^/]+| ...`)  
```javascript
  // ...
  options: {
    reporterOptions: {
      archi: {
        collapsePattern: [
          // lerna-like organization
          '^packages/bc-[^/]+/src/lib/[^/]+', // this one _before_ the src/[^/]+ one so it doesn't accidentally collapse directly under src
          '^packages/bc-[^/]+/src/[^/]+,
          '^packages/bc-[^/]+/lib/[^/]+',
          '^packages/shared-stuff/[^/]+,
          
          // nx based organisation; apps & libs
          '^apps/[^/]+/src/[^/]+,   
          '^libs/bc-[^/]+/src/[^/]+,   
        ]
      }
    }
  }
  // ...
```
- if the resulting graph is not too large angled lines ('orthogonal routing') instead of swoopy ones ('spline routing') increases legibility. You can pass that to dot directly (pass it `-Gsplines=ortho` on the command line) or in .dependency-cruiser.js in the dot and/ or archi reporter config (set `options.reporterOptions.archi.theme.graph.splines` to `"ortho"`). GraphViz' dot orthogonal routing algorithm tends to not scale very well, though (becomes slow), so ymmv.

1) In addition some teams organised their code primarily by functionality (search, select, pay), others organised by technical concepts (helpers, controllers, views) with functionality directly below it. Same for tests; sometimes in a separate folder altogether, sometimes directly next to the source code, each with their own naming patterns... For the visualization I ended up with an `exclude` filter that ignored everything that had a testing smel of testing (spec, test, \_\_tests\_\_, fixture(s), mock(s),
