### ISSUE TITLE
[question] how to exclude builtin node modules like fs?

### ISSUE THREAD

**Issue by Almenon** [sverweij/dependency-cruiser#61]
See above question.  The builtin node modules are grayed out so depcruise already recognizes them, there must be some option I'm missing that would let me exclude them from the dot diagram.

> depcruise --exclude "vscode" --output-type dot src | dot -T svg > dependencygraph.svg

![dependencygraph](https://user-images.githubusercontent.com/13080965/44622684-6a6bfc00-a872-11e8-8e35-f53fb2c25c57.png)

(_diagram of [arepl-vscode](https://github.com/arepl-vscode)_)

**Comment by sverweij** [comment]
hi @Almenon, a good question - definitely not apparent from the documentation. I'll add it to the FAQ.

B.t.w.: => What is the reason you want to keep them from your diagram?

#### how to ditch core modules from the output
Currently the only way to --exclude (/--do-not-follow) core modules in diagrams is with a regex. Typically something like `^[a-zA-Z0-9\_]+$` works (because typically only core modules resolve to something without path separators).

```shell
depcruise --do-not-follow node_modules --exclude "vscode|^[a-zA-Z0-9\_]+$" --output-type dot src | dot -T svg > dependencygraph.svg
```

<img width="804" alt="dot with " src="https://user-images.githubusercontent.com/4822597/44622970-b2673f00-a8c3-11e8-9f0f-4d91b24b11b7.png">


> B.t.w. dependency-cruiser indeed recognises core modules on a conceptually clearer level. Within [rules](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md) it _is_ possible to match core modules - `core` is one of the [dependency types](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#dependencytypes) there.

- I'll see if there's a more elegant way to do this (it might become an addition to the .dependency-cruiser.json format). 


#### Looking at your cli & diagram...
- I see you --excluded  `vscode`. Is that to avoid cluttering your diagram with the complete contents of the `vscode-extension-telemetry` module? In that case collapsing stuff in node_modules with `--do-not-follow` might help out.
- I've recently added a more richly coloured version of the dot reporter (`rcdot`) you might like better

command line:
```shell
depcruise --do-not-follow "node_modules" --exclude "^[a-zA-Z0-9\_]+$" --output-type rcdot src | dot -T svg > dependencygraph.svg
```

<img width="805" alt="screen shot 2018-08-26 at 00 08 06" src="https://user-images.githubusercontent.com/4822597/44622994-302b4a80-a8c4-11e8-85b2-c807424a0d45.png">

**Comment by sverweij** [comment]
b.t.w. I wish your project would've been around when I still wrote python - looks like a live-saver 👍

**Comment by Almenon** [comment]
Thanks for your very fast response.

>  What is the reason you want to keep them from your diagram?

I'm using the dependency graph to visualize the architecture; builtin node modules are not part of that.

> I see you --excluded vscode. Is that to avoid cluttering your diagram with the complete contents of the vscode-extension-telemetry module? In that case collapsing stuff in node_modules with --do-not-follow might help out.

I excluded vscode because it doesn't tell the viewer much; arepl-vscode is a vscode extension, so of course it is going to reference vscode.  VSCode made the diagram too busy visually.  And yes, I didn't want the vscode-extension-telemetry module either. I'm not using --do-not-follow because that excludes python-shell, which is a important part of arepl-backend.

Ugh, I just realized I'm one of those terrible customers with ultra-specific use-cases XD.

> I've recently added a more richly coloured version of the dot reporter (rcdot) you might like better

I like the blue in rcdot but the red is a bit glaring.

> b.t.w. I wish your project would've been around when I still wrote python - looks like a live-saver 👍

Thanks :D

Your project is really cool too, I wish all projects had a visual call graph rather than just a tangled mess of 1000+ line files.

**Comment by OlegAlexander** [comment]
Hello. I'm having the same issue. I'd like to exclude the core modules from the graph. I tried your suggestion to --exclude "^[a-zA-Z0-9\_]+$" and it works. However, doing that also removes orphan modules, which I'd like to keep. Is there a way to remove the core modules while keeping the orphans?

I've attached a screenshot. As you can see, --exclude "^[a-zA-Z0-9\_]+$" removes the assert core module, but also removes the inventory.js orphan module. 

![dependencycruiserexcludecoremodules](https://user-images.githubusercontent.com/42989765/49547112-b4637580-f896-11e8-9eba-b9b2cbddd318.jpg)

Thank you so much for creating dependency-cruiser!

**Comment by sverweij** [comment]
Thanks for raising this @OlegAlexander - it is indeed unexpected as the _exclude_ pattern doesn't match `inventory.js`. Can you share the complete command line script you used?

**Comment by sverweij** [comment]
@OlegAlexander I've reproduce the issue and created a new one for it #80 . I'll investigate (& hopefully come up with a fix) in the course of this week.
