### ISSUE TITLE
Question [VUE]: error not-to-unresolvable for dynamic imports of sfc files

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [sverweij/dependency-cruiser#625]
### Summary

There seems to be a different handling for dynamic imports regarding path aliases. When I have a dynamic import in routes that references a Vue component that has a path alias i get an error like:

`error not-to-unresolvable: src/router/routes.ts → pages/some-component.vue`

### Context

I'm trying to find unused imports and circular dependencies and this seems to be something that is not implemented or a false positive to me.

```ts
const routes: RouteRecordRaw[] = [
  {
    path: '/',
    component: () => import(pages/some-component.vue'),
  }
]
```

### Environment

- Version used: 11.10.0
- Node version: 16.15.0
- Operating System and version: Windows 10 10.0.19044

**Comment by sverweij** [comment]
Hi @sschneider-ihre-pvs - from only the input provided in the issue I can't reproduce the issue. Typically when dependency-cruiser is not able to find a path it's because it doesn't (yet) know where to look. The non-prefixed (`import('pages/some-compenent.vue')`) suggests the presence of a tsconfig, jsconfig or webpack config with aliasses - assuming the 'pages/some-component.vue' isn't located in `node_modules`. 

If dependency-cruiser _did_ get told where to find the `pages/...` components and still persists in not finding them I'd be _very_ interested in a minimal reproduction example (that includes the .dependency-cruiser.js, any tsconfig/ jsconfig/ webpack etc. configs).

**Comment by sverweij** [comment]
Hi @sschneider-ihre-pvs dependency-cruiser treats tsconfig.json & its extension mechanism exactly like `tsc` does (checked by [automated integration tests](https://github.com/sverweij/dependency-cruiser/blob/develop/test/config-utl/extract-ts-config.spec.mjs#L108)).
