### ISSUE TITLE
How to bypass index.ts files in dependency-cruiser to show real dependency in monorepo?

### ISSUE THREAD

**Issue by cesek-navisys** [sverweij/dependency-cruiser#649]
We are using monorepo as described bellow (nx btw) so the dependencies are not direct between the files but they use extra index.ts files with exports. This unfortunatelly **hides real dependency** between the files.

```
- libs
  - library1
    - src
      - index.ts (exports lib/*.ts)
      - lib
        - service1.ts
        - controller1.ts (
            imports {service1} from './service.ts';
          )
  - library2
    - src
      - index.ts (exports lib/*.ts)
      - lib
        - service2.ts (
            imports {service1} from '@library1'
          )
        - extra-service2.ts (
            imports {service2} from './service2.ts';
            imports {service1} from '@library1';
          )
        - controller2.ts (
            imports {service1} from '@library1';
            imports {service2} from './service2.ts';
          )
  - library3
    - src
      - index.ts (exports lib/*.ts)
      - lib
        - service3.ts
        - controller3.ts (
            imports {service3} from './service3.ts';
          )
        - handler3.ts (
            imports {service2} from '@library2';
          )
```

The **expected/required** output for "*service.ts" should be like this:

[![](https://mermaid.ink/img/pako:eNp9j70OgkAMgF-FdIZBRgYn3Zx0vaXcFbnkfkjpqYTw7p4JJv7FTm2_r2k7g46GoIHOxavukaU4HFUocoypPTMOfeFsy8jTZm0TX6ymtaJgftv1m11X1fZj8CaM1Teu_-PXtVCCJ_ZoTb5_fgAF0pMnBU1ODXWYnChQYclqGgwK7Y2VyNB06EYqAZPE0xQ0NMKJntLOYv7Fr9ZyB23IYjY)](https://mermaid.live/edit#pako:eNp9j70OgkAMgF-FdIZBRgYn3Zx0vaXcFbnkfkjpqYTw7p4JJv7FTm2_r2k7g46GoIHOxavukaU4HFUocoypPTMOfeFsy8jTZm0TX6ymtaJgftv1m11X1fZj8CaM1Teu_-PXtVCCJ_ZoTb5_fgAF0pMnBU1ODXWYnChQYclqGgwK7Y2VyNB06EYqAZPE0xQ0NMKJntLOYv7Fr9ZyB23IYjY)

If we **include index.ts files** the output is better but we would never know there is a real service2-->service1 dependency:

[![](https://mermaid.ink/img/pako:eNp1kLEOgjAQhl-luRkGYGNw0s1J1y4HPaQJFHK0CiG8uzVKBMGbmvu_-_KnI-SNIkihqJpHXiJbcb5II_x0LrsxtqWodMbIQ_Rev0YbRX0kwvAgOuK7zmkRrjdk1L4u_tHFS91-SL1lDLfIvPHMu9k3Wp94YHu9QZaOv_WTn4bJ151smiULGQRQE9eolf_18RVIsCXVJCH1T0UFuspKkGbyqGsVWjopbRuGtMCqowDQ2eY6mBxSy45m6KjRN6w_1PQEZOSULg)](https://mermaid.live/edit#pako:eNp1kLEOgjAQhl-luRkGYGNw0s1J1y4HPaQJFHK0CiG8uzVKBMGbmvu_-_KnI-SNIkihqJpHXiJbcb5II_x0LrsxtqWodMbIQ_Rev0YbRX0kwvAgOuK7zmkRrjdk1L4u_tHFS91-SL1lDLfIvPHMu9k3Wp94YHu9QZaOv_WTn4bJ151smiULGQRQE9eolf_18RVIsCXVJCH1T0UFuspKkGbyqGsVWjopbRuGtMCqowDQ2eY6mBxSy45m6KjRN6w_1PQEZOSULg)

If we **exclude index.ts** we lose the cross library dependency completely:

[![](https://mermaid.ink/img/pako:eNo1jr0OgzAQg18F3UwWxgyd2q1Tu2Y5kqNEyg86LrQI8e5NVfBk2Z8sb2CzI9AwhPy2I7I094dJTdVc-hfjNDbB94y8dv-YPsKoZuLFW-qUupz2qJMzCVqIxBG9q8vbrzAgI0UyoKt1NGAJYsCkvaJlcih0c14ygx4wzNQCFsnPNVnQwoVO6OqxfooHtX8BvSZAvg)](https://mermaid.live/edit#pako:eNo1jr0OgzAQg18F3UwWxgyd2q1Tu2Y5kqNEyg86LrQI8e5NVfBk2Z8sb2CzI9AwhPy2I7I094dJTdVc-hfjNDbB94y8dv-YPsKoZuLFW-qUupz2qJMzCVqIxBG9q8vbrzAgI0UyoKt1NGAJYsCkvaJlcih0c14ygx4wzNQCFsnPNVnQwoVO6OqxfooHtX8BvSZAvg)

  [1]: https://www.npmjs.com/package/dependency-cruiser

- Version used:
- Node version: 16.16.0
- Operating System and version: Windows 10

**Comment by rickihastings** [comment]
Hi @cesek-navisys, did you manage to find a solution to this problem? I'm encountering the same issue but struggling to find a solution.

**Comment by sverweij** [comment]
I notice I never answered this specific issue, although #638 and #896, which are closely related, if not the same issue did get an answer.

While it is technically possible to derive the dependencies barrel files are hiding (javascript interpreters can do it at least at runtime ...) it is by no means trivial (see e.g. https://github.com/sverweij/dependency-cruiser/issues/896#issuecomment-1881827884 for some examples)

The most obvious solution is to stop using barrel files (which has other benefits as well!), but I understand that that won't be a viable solution in many cases, if only because of the amount of work involved.

Expanding dependency-cruiser with the capability is another option. Even though it goes against the original philosophy (do one thing, do that well), it would be an interesting challenge. Two things hold me back from adding it - the aforementioned complexity and _time_, or rather lack thereof as I also have to give priority to other things in life at the moment.
