### ISSUE TITLE
Feature request: Make depcruise more usable without installation

### ISSUE THREAD

**Issue by danielo515** [sverweij/dependency-cruiser#688]
Hello again.
As usual, depcruise helped me understand a complex codebase again, thanks for that.

### Context

I am usually in the need to quickly get visualisations of codebases that I am not able or don't want to install depcruise, nor want to add a depcruise configuration

### Expected Behavior

Using depcruise from npx is not easy, and does not have (as far as I know) much functionality. Some of the more advanced and needed features like interactive html graphs, straigth lines, colored stuff are not available to use from npx. This is mainly because they require command piping, and npx does not understand how to do that. npx is neither able to recognize some of the depcruise subcommands like `depcruise-wrap-stream-in-html`

### Current Behavior

Already explained above

### Possible Solution

Maybe make the main cli accept more options, and do the required calls internally. An option to use presets will be lovely.

### Considered alternatives

copy pasting is the only one that I know of 😄

**Comment by sverweij** [comment]
hi @danielo515 thanks for reaching out on this topic.

For the best results I generally do not recommend to use dependency-cruiser with `npx` (or even as a global install for that matter) - but instead to use it as a local install. That way dependency-cruiser can look through the same 'glasses' as node, typescript, babel, webpack, vue etc do - also having available exactly the same (versions) of your transpilation chain available.

`npx` does b.t.w. have some options - on unix-y systems `man npx` will show them, otherwise possibly `npm help exec` might be of help. It e.g. enables you to specify a command you might want to run from a package (with -p/ --package)

```shell
npx dependency-cruiser -c -T dot src \
     | dot -T svg \
     | npx -p dependency-cruiser@latest depcruise-wrap-stream-in-html \
     | browser
```

B.t.w. I've found no issues piping commands through node programs called with npx.

Straight lines b.t.w. are something that `dot` will do for you. It's of course possible to specify it within a .dependency-cruiser.js, but `dot` also takes command line parameters. E.g. to influence how lines are drawn with `-Gsplines`. Piping a dot program as emitted by dependency-cruiser through `dot -Gsplines=ortho -T svg` will get you straight lines (caveats about max sizes that `dot` can stomach for orthogonal routing still apply):


```shell
npx dependency-cruiser -c -T dot src \
     | dot -Gsplines=ortho -T svg \
     | npx -p dependency-cruiser@latest depcruise-wrap-stream-in-html \
     | browser
```

**Comment by sverweij** [comment]
b.t.w. your suggestion to make configure-less use possible is a good one. It will never be  possible to be 100% correct - for this the variability in JavaScript land is too big. But with educated guesses (like what `--init yes`  does) it should be possible to cover a lot of use cases.

**Comment by danielo515** [comment]
> That way dependency-cruiser can look through the same 'glasses' as node, typescript, babel, webpack, vue etc do - also having available exactly the same (versions) of your transpilation chain available.

Fair points.



> `npx` does b.t.w. have some options - on unix-y systems `man npx` will show them, otherwise possibly `npm help exec` might be of help. It e.g. enables you to specify a command you might want to run from a package (with -p/ --package)

I was not aware of this, and indeed it can reduce drastically my problems when using depcruise.

> B.t.w. I've found no issues piping commands through node programs called with npx.

Nah, you're right. My problems were more in the line of npx not finding the subcommands. Usually I also use yarn, which has way worse support for this kind of flows.

> The browser command from the snippets above is this nifty thing from defunkt: [browser](https://gist.github.com/defunkt/318247) - with home-brew installable with brew install browser

Oh, I was wondering why I didn't have it by default 😄 

As always, thank you for your answers and this project. You can close the issue if you want

> but `dot` also takes command line parameters. E.g. to influence how lines are drawn with `-Gsplines`. Piping a dot program as emitted by dependency-cruiser through `dot -Gsplines=ortho -T svg` will get you straight lines (caveats about max sizes that `dot` can stomach for orthogonal routing still apply):

Yes, I saw it in some of your examples, thanks. However, I think I will try to avoid giving `dot` any extra work, it is already the slowest part on the pipeline.

**Comment by sverweij** [comment]
> Usually I also use yarn, which has way worse support for this kind of flows.
yarn emits its progress feedback to stdout instead of to stderr. This makes the feedback gets piped along with regular output of programs it invokes. If you pass yarn `--silent` it stops doing that - yielding more expected results  (ask me how I know 😉).
