### ISSUE TITLE
Issue: default config seems to be ignored despite it is named with the expected default name

### ISSUE THREAD

**Issue by danielo515** [sverweij/dependency-cruiser#690]
I was a bit confused about why my configuration changes were not taking effect. Then I decided to try to provide the `--config path/to/config` option, just to test, and then things started to work as expected. My file is named `.dependency-cruiser.js`

### Expected Behavior

I expect the default config file to be used

### Current Behavior

Seems to use the default configuration

### Steps to Reproduce (for bugs)

I have this in my package.json scripts

```
    "dc": "depcruise --version && depcruise --ignore-known -T err src/*/{*.js,src}",
    "dc:baseline": "depcruise --version && depcruise-baseline src/*/{*.js,src}",
    "dc:archi": "depcruise --ignore-known -T archi src/*/*.js | dot -T svg | depcruise-wrap-stream-in-html > deps.html",
    "dc:dot": "depcruise --ignore-known -T dot src/*/*.js | dot -T svg | depcruise-wrap-stream-in-html > deps.html"

```

Running any of those seems to use the default configuration rather than my config file.

### Your Environment

- Version used: 12.0.1
- Node version: 16
- Operating System and version: Macos Ventura
- Link to your project: private one

**Comment by sverweij** [comment]
Hi again @danielo515 :-)

- Passing `--config` _with_ a parameter will take that parameter as a filename to read the configuration from.
- Passing `--config` (or `-c`) without a parameter will make dependency-cruiser look for the default configuration file name (searching, for a file named either .dependency-cruiser.json, .dependency-cruiser.js or .dependency-cruiser.cjs (in that order, also for backwards compatibility reasons))
- By default, when the `--config` option is not passed dependency-cruiser will not use _any_ configuration file. 

That last one is non-obvious and exists only because of backwards compatibility. It's somewhere on the _breaking changes to do one day_ list to make this automatically read the default config file name. In parallel we'd then also have to introduce a --no-config option to keep the same functionality.

**Comment by danielo515** [comment]
That is more or less what I deduced from reading the examples, but I swear I didn't saw anything in the docs detailing that 😄 
Im the kind of lazy person, and if I can save myself specifying a default option, I will. When I read `the default configuration file is X` I don't expect to have to tell any program to use it in any way, that is why I find this so confusing.
Maybe, until you find the way to do a breaking change in a good way, you could highlight this in the docs a bit more?

**Comment by sverweij** [comment]
Agree @danielo515 - I've added a little blurb to the cli documentation (see linked commit).

**Comment by danielo515** [comment]
That’s perfect, thank you
