### ISSUE TITLE
Add dynamic import support

### ISSUE THREAD

**Issue by liyuanqiu** [sverweij/dependency-cruiser#72]
### Expected Behavior

Add dynamic import support. It is widely used in lazy loading and code splitting scenarios.

### Current Behavior

Now all dependencies imported using `import()` won't be added to the graph.

### Context

import() now is a proposal:
https://github.com/tc39/proposal-dynamic-import

Webpack lazy loading and code splitting:
https://webpack.js.org/guides/lazy-loading/
https://webpack.js.org/guides/code-splitting/

React code splitting
https://reactjs.org/docs/code-splitting.html

**Comment by sverweij** [comment]
hi @liyuanqiu thanks for raising this. It's a long standing wish (see [this item](https://github.com/sverweij/dependency-cruiser/projects/1#card-6999289) on the backlog) - for typescript (where it's a first class citizen already)- and this issue helps me look into it again.

The reason dependency-cruiser doesn't support it directly yet, is because it uses acorn to parse javascript. `acorn` _will_ support dynamic `import()`, but only when the tc39 proposal is in stage 4 (source: Marijn's response in  [issue 477 in the acorn repo](https://github.com/acornjs/acorn/issues/477)). Currently the proposal is in stage 3, however. B.t.w. 

That said, there's options I can look into to work around the issue. No guarantees, though...
- Babel down the import to a construct that's part of official ecmascript (for the purposes of dependency-cruiser a simple require would suffice).
- Use typescript for the same.
- Swap out acorn for esprima or espree (esprima seems to support it according to [this pull request](https://github.com/jquery/esprima/pull/1740) - although esprima doesn't seem to be actively maintained anymore (last commit: Jun 11 this year). espree doesn't support it either according to (issue 344 in the espree repo)[https://github.com/eslint/espree/issues/344]).

B.t.w. if you're using typescript dependency-cruiser already supports it - you can put `target` on `ES3` in your tsconfig.json and pass it to depcruise with the `--ts-config` option.

**Comment by liyuanqiu** [comment]
Thank you, I'll give a try to the options you mentioned.
