### ISSUE TITLE
GraphViz error: report error ibpath/shortest.c:314: triangulation failed libpath/shortest.c:180: source point not in any triangle

### ISSUE THREAD

**Issue by lqzerogg** [sverweij/dependency-cruiser#728]
### Expected Behavior
It should draw the svg successfully

### Current Behavior
report error, informations are below:

ibpath/shortest.c:314: triangulation failed
libpath/shortest.c:180: source point not in any triangle
Error: in routesplines, Pshortestpath failed
libpath/shortest.c:314: triangulation failed
libpath/shortest.c:180: source point not in any triangle
Error: in routesplines, Pshortestpath failed
libpath/shortest.c:314: triangulation failed
libpath/shortest.c:180: source point not in any triangle
Error: in routesplines, Pshortestpath failed
Error: lost src/pages/index.ts src/ui/pages/core/confirm/index.tsx edge
Error: lost src/pages/index.ts src/ui/pages/core/finance/success.tsx edge
Error: lost src/routes/pc-ma.tsx src/ui/pages/my-account/account-summary/ma-view/index.tsx edge

### Steps to Reproduce (for bugs)

1. init steps: 
✔ Where do your source files live? … src
✔ Do your test files live in a separate folder? … yes
✔ Where do your test files live? … build
✔ Looks like you're using a 'tsconfig.json'. Use that? … yes
✔ Full path to your 'tsconfig.json › tsconfig.json
✔ Also regard TypeScript dependencies that exist only before compilation? … yes
  ✔ Successfully created '.dependency-cruiser.js'
2. options configurations:
```JSON
{
  options: {

    /* conditions specifying which files not to follow further when encountered:
       - path: a regular expression to match
       - dependencyTypes: see https://github.com/sverweij/dependency-cruiser/blob/master/doc/rules-reference.md#dependencytypes-and-dependencytypesnot
       for a complete list
    */
    doNotFollow: {
      path: 'node_modules'
    },
    "includeOnly": "^src/",
    "reaches": "testforit",
  }
}
```
3. run command line

npx dependency-cruise src -c .dependency-cruiser.js -T dot | dot -T svg > internal-dependency-graph.svg

### Context

just want to know how to get rid of this problem, or avoid of such problem

### Your Environment

- Version used: 12.5.0
- Node version: v18.12.1
- Operating System and version: macOS Monterey
- Link to your project:

**Comment by sverweij** [comment]
hi @lqzerogg thanks for raising this. The error messages are thrown by [GraphViz](https://graphviz.org/) dot. Dependency-cruiser just emits the `dot` graph description, GraphViz translates it into a nice picture. As such there's not much that can be done in dependency-cruiser  to make these errors go away/ make GraphViz work. When I bumped into these problems in the past it was usually because the graph I was trying to emit was on the large side; GraphViz is nice and robust, but also has its limits. Graphs that are that large tend to not that informative either. Strategies to cope:
- instruct dependency-cruiser to emit a higher level graph e.g. with something like [--collapse](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--collapse-summarize-to-folder-depth-or-pattern) (on the cli, or its [collapse](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#collapse-summarize-to-folder-depth-or-pattern) option counterpart) or the [collapsePattern](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#summarising-collapsepattern-dot-and-archi-reporters) reporter option.
- if you want to see details of a part of your source code: only include that/ exclude parts of the code you might not be interested in (e.g. test files?, mocks?).
