### ISSUE TITLE
change UTF-16 default format to something else

### ISSUE THREAD

**Issue by j2l** [sverweij/dependency-cruiser#76]
First of all, thank you! 
I was waiting for this thing for a long time and din't find it until now :(

`depcruise --exclude "^node_modules" --output-type rcdot src > test.dot`
produces a UTF-16LE file (visible in Notepad++ / Encoding menu).

It breaks gv2gml and dottoxml conversions to gml format

Once converted to UTF-8 or ANSI and saved, you can user converters.

### Expected Behavior
`-encoding "ANSI" ` and/or `-encoding "UTF8"`?

**Comment by sverweij** [comment]
hi @j2l - I hope 

Thanks for raising this issue - I see that when dc writes to stdout it doesn't specify an encoding, and probably falls back to something default for node (or something default for the OS you're on).

It should be an easy fix - expect it to hit npmjs in the coming days (I'll let you know in this thread).

**Comment by j2l** [comment]
Great! Thanks @sverweij!
FYI, I use Win10.

May I ask a future feature?
Do you think you could implement gml export format directly?
Because both gv2gml and dottoxml remove clusters, grouping, etc.
It ends up ruining the dc work :(

**Comment by sverweij** [comment]
Hi @j2l I'm not familiar with gml (or the output or dottoxml which I gather to be gxl?) - I found [some](https://en.wikipedia.org/wiki/Graph_Modelling_Language) [references](https://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf), and I'm intrigued. 

=> What would you be using the gml output for?

**Comment by sverweij** [comment]
hi @j2l I've published version 4.7.1-beta-1 to npm with the beta tag (so installing dependency-cruiser@4.7.1-beta-1 should get you the version with the fix.

I don't have machines where this borked (with or without utf8 explicitly passed - both work on all my machines + on the windows & linux CI's dependency-cruiser runs on) - so if you could give it a spin & report back whether it fixes your issue, that would be really helpful.

**Comment by j2l** [comment]
Hi @sverweij , wonderful!
Thank you very much for this fast response. I'll test that ASAP.
I mainly using gml in [yEd](https://www.yworks.com/) because of it's auto-arrange function.
graphviz auto arranges following stricter rules and sometimes, you need a different view on the libraries :)

**Comment by sverweij** [comment]
### This issue
I'll consider this issue fixed (the fix is part of the 4.7.0 production version) - let me know if there's reasons to assume otherwise

### GML support
hi @j2l I've taken a peek at gml - I didn't notice an option there to nest nodes, but I might have missed something. If it does, I would welcome a PR to add gml as an output format.  I've put it [on the backlog](https://github.com/sverweij/dependency-cruiser/projects/1#card-15540048) as a _PR welcome_ future feature.

GraphML (the internal format yEd seems to use from what I understand of their website) does support nesting for sure. GraphML as an output format is welcome as well - I've put an [item on the backlog](https://github.com/sverweij/dependency-cruiser/projects/1#card-15540094) as a future feature.

I _am_ looking into other ways to represent the graph, though. Especially for bigger code bases the current GraphViz output is not ideal. It can partly be solved by using other graphviz layout engines (`osage` and `fdp` sometimes yield usable graphs - see [the samples in dependency-cruiser's package.json](https://github.com/sverweij/dependency-cruiser/blob/develop/package.json#L55) as an example), but not entirely - so I'm trying cytoscape (which can be made interactive with relative ease) but yEd (read: GraphML) might fit the bill as well.

**Comment by j2l** [comment]
I didn't try again yet but I'm sure you nailed it 😄 
Yeah, indeed, GZ is wonderful tool but result is unreadable, here's my SVG result on a 4K screen:
![image](https://user-images.githubusercontent.com/65325/49641429-6bcfc780-fa10-11e8-99ea-d4a7ee3385ad.png)

and the same graph, rearranged with yEd (missing groups though):
![image](https://user-images.githubusercontent.com/65325/49641526-a8032800-fa10-11e8-88bb-709dab677835.png)

The second one I printed on A3 and is readable, the first one, even with glue, is unusable.

**Comment by sverweij** [comment]
Thanks for sharing that.

Nesting typically complicates auto layouting quite a bit idd. The default hierarchical one dot uses is not always the best either for big graphs - and I have experiences similar to what you show above. I'm curious what yEd would make of it.

In the mean time here's what I do for one particularly gnarly code base. There's a lot of dependencies, that go all over the place (I mentioned it was gnarly, didn't I :-) ?) - so I make the edge colors a tad lighter with graphviz' command line switch `-Ecolor=gray`. Here's the incantation for the fdp layout algorithm. It typically fits on an A3 while remaining legible (at least for the young paduans out here :-) ):

```sh
depcruise --validate --exclude \"^[a-z]+$|node_modules|test|spec\" -T rcdot -- src | fdp -Ecolor=gray -GK=0.1 -Gsplines=true -T svg > dependencies-fdp-layout.svg
```

And sometimes the osage algorithm gives better results
```sh
depcruise -v -x "^[a-z]+$|node_modules|test|spec|mock" -T rcdot -- src | osage -Ecolor=gray -Gpack=16 -GpackMode=array2 -T svg > dependencies-osage-layout.svg
```

None of them perfect, so I'll keep searching - I'll give yEd a spin if I have some downtime - thanks for putting me on to its trail!
