### ISSUE TITLE
Feature request: Can we have a setting where we can increase space between the too close to see arrows? 

### ISSUE THREAD

**Issue by TejushAegis** [sverweij/dependency-cruiser#814]
Basically when Im trying to see my project, im seeing arrows that are hard to make sense of. They are overlapping and sometimes totally hard to distinguish. It would be great if this was a feature, or maybe theres already something like that?

**Comment by sverweij** [comment]
Hi @TejushAegis thanks for your  question.  I assume you let  dependency-cruiser emit  a `dot` file  of  your  dependency  graph and use GraphViz dot to display it? In that case there's a lot of possibilities to tweak how the graph is displayed. GraphViz is [well documented](https://graphviz.org/documentation/) - and quite elaborate, so I can't possibly cover all of that, but I  can highlight a few  options  that have helped  me in the past. You can apply these attributes  and tweaks  either on the command line  as options you pass to `dot` command, or  as part of the dependency-cruiser configuration's [reporter options](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#theme-dot-ddot-and-archi-reporters)

- using 'orthogonal routing' for the lines typically cleans up your graph. The algorithm doesn't scale well to > 100 nodes, but when it works it looks quite nice. E.g. compare [this overview of yarn](https://sverweij.github.io/dependency-cruiser/assets/berry-high-level-dependencies.html) with orthogonal routing vs [this one with regular 'splines'](https://raw.githubusercontent.com/sverweij/dependency-cruiser/main/doc/real-world-samples/tslint-without-node_modules.png)

You can set this in .dependency-cruiser.js in the options section e.g.

```javascript
// ...
  options: {
    reporterOptions: {
      dot: {
        theme: {
          graph: {
            splines: "ortho"
          }
        } 
      }
    }
  }
// ...
```

- In that theme section you can apply more tweaks. If arrows overlap because the module(s) they point to are too small to fit them all on a side, you can make the size of the modules a bit bigger. In GraphViz terminology modules are rendered as _nodes_, so yoou can target that:

```javascript
// ...
  options: {
    reporterOptions: {
      dot: {
        theme: {
          graph: {
            splines: "ortho"
          },
          node: {
            height: 0.5 // height in inches ¯\_(ツ)_/¯
          }
        } 
      }
    }
  }
// ...
```

- You might have noticed [the overview of yarn](https://sverweij.github.io/dependency-cruiser/assets/berry-high-level-dependencies.html) is a little bit interactive; when you hover over a line it highlights that line lights up, if you right click it that line stays that way. This is done with [depcruise-wrap-in-stream](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#depcruise-wrap-stream-in-html) - a tiny program that wraps the svg dot emits in a bit of html to make it more interactive.

Hope this helps!
