### ISSUE TITLE
Question: How to detect missing package.json entries for type imports

### ISSUE THREAD

**Issue by lo1tuma** [sverweij/dependency-cruiser#837]
I’m using the `no-non-package-json` rule

```
module.exports = {
  name: "no-non-package-json",
  severity: "error",
  from: {},
  to: {
    dependencyTypes: ["npm-no-pkg", "npm-unknown"],
  },
};
```

But it seems like it doesn’t work for type-only imports which point to a node module that is not listed in the `package.json`.

Is there a way to do this?

**Comment by sverweij** [comment]
Hi @lo1tuma thanks for asking! Slightly worried this all of a sudden stopped working, I created a reproduction repo: https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/837 - and it still seems to work ok.

Things that might prevent the rule from triggering
- dependency-cruiser ignores type only imports because the `tsPreCompilationDeps` option is set to `false`
- there's another package (the real one) it can resolve the import to. E.g. when both the `@types/snodash` and the `snodash` package exist and is in package.json, and `@types/snodash` exist but _isn't_ in package.json, any reference to `snodash` will still happily resolve to the `snodash` package, even, though it's a type only import.

**Comment by lo1tuma** [comment]
Hi @sverweij thanks for taking the time and looking into this. Today I’ve tried it again and for whatever reason it works. I’ve also tried to setup another project to reproduce the issue I had yesterday with the exact same dependencies (in this case it was `type-fest`), but I cannot reproduce it anymore. So I guess I did something completely wrong yesterday while I was debugging some type issues I had and at some point I’ve noticed I had a very outdated version of type-fest because it was not part of my package.json, after that I’ve added the `no-non-package-json` rule and for whatever reason I haven’t seen the error reported. But as I said, today it works like a charm.
