### ISSUE TITLE
Question: can dependency-cruiser do with less 3rd party dependencies?

### ISSUE THREAD

**Issue by jimmywarting** [sverweij/dependency-cruiser#839]
there are so many dependencies https://npmgraph.js.org/?q=dependency-cruiser@10.9.0
any chance to reduce it?

require more modern syntax?
help upstream packages get rid unnecessary stuff?

every sub dependency you don't have direct control over is a potential vulnerable risk

**Comment by sverweij** [comment]
Hi @jimmywarting thanks for sharing your concern. Indeed each third party dependency dragged in is a trade-off, and I re-evaluate those from time to time; e.g. recently `handlebars` was replaced by (just as maintainable) vanilla JavaScript and I have my eye on replacing commander with `parseArgs` from `node:util`. I can't do that with everything though - writing my own JavaScript or JSON schema parser (or even resolver) from scratch is interesting and satisfying work - but then I'd never ship :-) 

Regarding modern syntax: Since version 13 dependency-cruiser is ESM.  

It seems the graph is already smaller with version 13.1.5 as compared to the version 10.9.0 you linked - so it might be that one would already be closer https://npmgraph.js.org/?q=dependency-cruiser@13.1.5 ?

=> That said, there's always room for improvement! Do you have suggestions for what can be removed and/ or replaced?

**Comment by jimmywarting** [comment]
i often try to stay away from anything Ijharb builds, 
He thinks that many user still use NodeJS v0.11 or IE8 still so every bit and pieces has to be implemented all the way through ES3 to ES6, here is a [proof](https://npmgraph.js.org/?q=string.prototype.replaceall) of that. 
Asking him to upgrade something to get rid of something that isn't needed anymore is a NO-go. 
but he dose not have a huge foothold on this project at least.

nevertheless... Looking at the packages with the most dependencies we have from top to bottom:
1. [glob](https://npmgraph.js.org/?q=glob@10.3.3) (27)
3. [tsconfig-paths-webpack-plugin](https://npmgraph.js.org/?q=tsconfig-paths-webpack-plugin@4.1.0) (14)
2. [rechoir](https://npmgraph.js.org/?q=rechoir@0.8.0) (7)
4. [ajv](https://npmgraph.js.org/?q=ajv@8.12.0) (6)

Maybe this are the things we can focus on perhaps maybe trying to replace, or maybe even help out contributing to?

Personally, i have never been a huge fan of any glob or any other 7 variant of them out there...
i think it's too big, too fancy and too much over engineered for what you mostly use it for. 
Most of the time it can be achieved with a own simple built recursive function / generator to achieve the same goal. 
ofc you will not have the same luxury and functionality as any glob library have if you roll your own. but sometimes less is more. 

Node have a own built in way of scanning all files recursively now:
- https://nodejs.org/dist/latest/docs/api/fs.html#fspromisesreaddirpath-options
- thanks to [nodejs/node#34992](https://togithub.com/nodejs/node/issues/34992) and [nodejs/node#41439](https://togithub.com/nodejs/node/pull/41439)

unfortenly it req NodeJS v20.1.0

Anyhow. i like this solution that anyone can implement right now that was suggested in nodejs issue
```js
async function* listDir(path) {
  const dir = await opendir(path);
  for await (const dirent of dir) {
    const name = join(path, dirent.name);
    if (dirent.isDirectory()) {
      yield* listDir(name);
    } else {
      yield name;
    }
  }
}
```

Building on top of that you could use this like so:
```js
for await (const path of listDir(path)) {
  // do something with full absolute file path
}
```
if you like you can expand on this and include a filter fn and slam in a small if-condition

```js
async function* listDir(path) {
  const dir = await opendir(path);
  for await (const dirent of dir) {
    const name = join(path, dirent.name);
    if (filter && !filter(name, dirent.isDirectory())) continue
    if (dirent.isDirectory()) {
      yield* listDir(name);
    } else {
      yield name;
    }
  }
}

function filter (path, isDir) {
  return path.includes('.js') || path.includes('build')
}

for await (const path of listDir(path, filter)) {
  // do something with full absolute file path
}
```

it's just a suggestion.

**Comment by sverweij** [comment]
Hi @jimmywarting thanks for the elaborate suggestions!

### glob

Indeed there's an opportunity to improve. I'd _love_ to get rid of it (what business does it have using `foreground-child` and `cross-spawn`?). Dependency-cruiser _does_ use the glob expansion capabilities of node-glob (and not just the directory traversal stuff) though, so we'd need to find an alternative to prevent loss of functionality. 

[`picomatch`](https://npmgraph.js.org/?q=picomatch@2.3.1) seems to be a sturdy, small and dependency-less replacement for just that part. 


### tsconfig-paths-webpack-plugin

After trying some other libraries I've settled on this one for doing the hairy tsconfig/ jsconfig paths resolutions. 


### rechoir

For reasons I don't understand some libraries seem to want to have configuration passed in every esoteric programming paradigm out there - beside json and javascript also typescript (which is sort-of reasonable, I guess) also coffeescript, livescript, .... As we need to read some of the configurations for e.g. webpack, we need the dark magic they use as well.

### ajv

Is doing json schema validation with quite ok error reporting. There's alternatives out there, but last I looked they were not maintained anymore (tv4, json-schema, jsonschema), have just as many dependencies (z-schema) or didn't look as robust as ajv. Alternatives still welcome, though as apart from the # of transitive dependencies ajv is also not small itself (1.95Mb according to https://www.npmjs.com/package/ajv).

**Comment by sverweij** [comment]
☝️ just replaced glob with picomatch. An `npm i` shows that the total number of installed 3rd party dependencies was reduced with 24. As a bonus startup speed as well as the speed of a specific step seem to have improved with significant numbers. See the PR linked above for details. 

This will be part of the upcoming dependency-cruiser 14.x release (a major bump because it also stops node 16 & 19 support for other reasons).
