### ISSUE TITLE
Unable to generate a usable chart

### ISSUE THREAD

**Issue by buremba** [sverweij/dependency-cruiser#87]
Thanks for the great library. I'm trying to use it for our Vue project but even though the graph it generates is meaningful, it's impossible to track down the arrows and connections between the nodes.

### Expected Behavior
I should be able to keep track of connections easily even though the graph will be huge.

### Current Behavior
![image](https://user-images.githubusercontent.com/82745/50423867-6f66a980-086c-11e9-9402-ab6dbb1f302d.png)

It kinda looks like this: :)
![image](https://user-images.githubusercontent.com/82745/50423879-a3da6580-086c-11e9-93fa-f96d71e2579f.png)

### Possible Solution
We can make the graph much bigger or make the SVG interactive so that when I click the graph I can follow how the lines are connected to each other. I'm not sure how to do that using Graphviz but here is a D3 example: http://bl.ocks.org/robschmuecker/7880033

### Steps to Reproduce (for bugs)
I can't share the SVG due to privacy reasons but let me know if you need more info. It probably happens in case a node has too many dependencies that are connected to each other.

### Your Environment

* Version used: Latest
* Graphviz version: 2.40.1 (20161225.0304)
* Link to your project: Private

**Comment by sverweij** [comment]
hi @buremba  - thanks for your feedback. LOL at the quiz sample :-) 

I feel your pain - it strengthens my resolve to cook an alternative graph representation ([2nd spot on the backlog](https://github.com/sverweij/dependency-cruiser/projects/1#card-1914259)) that is easy to use with collapsable folders, highlight on select or hover of edges and nodes, default collapse level. The reason dependency-cruiser still generates graphviz & SVG is that other options I've tried didn't support nesting. I'm hopeful that this Christmas holiday cytoscape.js or the stuff the guys at [graphql-voyager](https://apis.guru/graphql-voyager/) pulled off with graphviz/ svg and some spit will yield something useful for spelunking _any sized_ code bases.

### in the mean time ...
there's some tweaking I have used on bigger code bases that might be helpful:
- Tweaking the edge color to be slightly transparent (pass -Ecolor=#00000077 as a parameter to dot)
- Adding a bit of css to the top of the generated svg (manually - I know, not ideal :-/) so hovering edges highlights them ([sample result here](https://sverweij.github.io/dependency-cruiser-dependency-graph.svg) ) - in combination with slightly thicker edges (`-Epenwidth=2`) surprisingly useful.
- Using an alternative graphviz layout engine - see [a subthread of issue 76](https://github.com/sverweij/dependency-cruiser/issues/76#issuecomment-445250862) for some examples - and applying above two tricks ([sample result for the 'fdp' algorithm here](https://sverweij.github.io/fdp-dependency-cruiser-dependency-graph.svg) )

#### command line sample
```sh
depcruise --validate --exclude "(node_modules|^[a-z]+$)" --output-type rcdot bin src | dot -T svg -Ecolor=#00000077 -Epenwidth=2 > dependency-cruiser-dependency-graph.svg
```

(P.S. I've used the `--output-type rcdot` instead of the default dot, as that colors various types of modules (like .vue, jsx etc) - which might help visual grepping a bit as well)


#### css tweak
Added directly below the <svg> tag:
```svg
<style>
     .edge:hover path{
         stroke:fuchsia;
         stroke-width:3;
         stroke-opacity:1;
     }
     .edge:hover polygon  {
         stroke:fuchsia;
         stroke-width:3;
         fill:fuchsia;
         stroke-opacity:1;
         fill-opacity:1;
     }
 </style>
```
