### ISSUE TITLE
TypeScript absolute imports within project are shown as duplicate red boxes

### ISSUE THREAD

**Issue by blixt** [sverweij/dependency-cruiser#90]
First of all, thanks for working on this awesome utility!

I've tried running this on a big project and also have issues like #87, but more importantly, the graph is divided into two clusters due to some inconsistency between how the TypeScript compiler resolves modules and how `depcruiser` does it.

Imports like this:

```typescript
import { appServices } from "./AppServices"
```

End up like this:

<img width="456" alt="screen shot 2019-01-04 at 23 14 47" src="https://user-images.githubusercontent.com/158591/50713998-5a152a80-1077-11e9-842e-09431c9ccc96.png">

But imports like this:

```typescript
import { appServices } from "app/AppServices"
```

End up as a duplicate in a different location like this:

<img width="205" alt="screen shot 2019-01-04 at 23 14 19" src="https://user-images.githubusercontent.com/158591/50714026-6e592780-1077-11e9-9f48-51af6b8d9862.png">

**Comment by sverweij** [comment]
Hi @blixt - thanks for reaching out with this.

There's not enough details for me to be sure, but my best guess is that telling dependency-cruiser where your tsConfig lives will resolve it.

You can do that with a command line parameter (`--ts-config`) or in the dependency-cruiser config (the `options.tsConfig` key - you'll see it at the bottom of the default one `depcruise --init` creates for you; just uncomment it). I've included an extremely simple sample project below.

Let me know if that worked or if you ran into other issues.

### background
For TypeScript by default module references that don't start with a `/` (absolute path) or `.` refer to something in `node_modules`. That is, _unless_ the TypeScript environment is configured differently. E.g.:
- There's a `baseUrl` key in the tsConfig
- There's a `paths` key in tsConfig  that re-maps `app` to a relative path

If you pass the tsConfig to dependency-cruiser it'll know to use these as well.

### sample project with configs
Here's a sample project that uses both a `baseUrl` and a `paths` key to re-map things
[dependency-cruiser-issue-90.zip](https://github.com/sverweij/dependency-cruiser/files/2729403/dependency-cruiser-issue-90.zip). If (after `npm i`-ing) you run the `depcruise` or `depcruise:graph` scripts you'll see the module resolution works as expected.


P.S.
In a next version of the --init command dependency-cruiser will try to detect the presence of ts and webpack configs and incorporate them in the config it generates.

**Comment by sverweij** [comment]
dependency-cruiser is idd able to generate graphs that, while valid, are too big/ complex for graphviz to handle (even with other algorithms, like `fop`). It's one of the other reasons I'm looking for an alternative. That said - the resulting graph (even when graphviz would be able to render it) might not be very useful exactly because of its size. 

What's the goal you want to achieve with the output? (I'm genuinely curious - it's feedback from people like you that is most useful in determining how to improve dependency-cruiser)

The best I can offer a.t.m. is strategies to circumvent the problem from occurring e.g.
- exclude all test files, mocks and fixtures from being investigated (i.e.`--exclude "node_modules|\.spec\.ts|fixtures|\.mock\.ts"`) - given there's things like these in the code base
- if there's especially deep or big (sub) systems in the repo that put these behind a `--do-not-follow` (`--do-not-follow "report|scarysubsystem") so they do show up, but hide their internals
- initially limit the depth of modules cruised (using `--max-depth`, maybe starting with 3 and working up till something useful shows up)

As to the other points:
- I see how the --help text is confusing here with the --ts-config default.  I'll think of a way to update it to make it more clear (or make it pick up a tsconfig by default - which would maybe easier in use - but also be a breaking change)
- as you noticed - the difference between dot and rcdot is not that big- it's just the colouring to help visual gripping. Structurally their identical as far as graphviz would be concerned.

HTH

**Comment by blixt** [comment]
The reason I found and used dependency-cruiser was that during a big refactor I wanted to confirm that all dependency chains were correct (that certain modules were completely independent from others). So most importantly I wanted to audit the lines going between directories, which in our case is the logical unit of inter-dependent code.

Thanks for your suggestions! I will play with these options to see if I can get `dot` to handle the output.

I hope that you find alternatives that work better for huge projects. Maybe something interactive since like you said a big project is difficult to grok, but if you can zoom and filter the graph interactively it would be way more manageable.
