### ISSUE TITLE
Make it work without installation

### ISSUE THREAD

**Issue by gentlee** [sverweij/dependency-cruiser#949]
Would be nice to just call:

`npx dependency-cruiser src`

to show the graph, without the need of installing anything.

### Context

I don't want to install and then remove this package if I want it to be used once.

### Expected Behavior

Just run `npx dependency-cruiser src` and get graph

### Current Behavior

Need to do installation steps then remove it.

**Comment by sverweij** [comment]
Hi @gentlee thanks for the suggestion. 

dependency-cruiser's primary use case is to run it as part of a permanent setup. 
Besides, running it as a one-off  with e.g. `npx` comes  with some complications:


- For TypeScript (Vue, Svelte, CoffeeScript, ...) projects you will need the appropriate transpilers. By design dependency-cruiser does not ship these  because  (1) whatever it ships it will in almost all cases be a different version as you're  actually using, resulting in subtle or not-so-subtle issues (2) shipping  all these compilers will make dependency-cruiser's installed/ download size _huge_ (3) it'll for sure ship  compilers you don't use too (e.g. if  you use vue, the svelte  compiler will be dead  weight).
- As there's close to zero standardization in JavaScript land there's a Gödelset of ways to decide where to find modules (think tsconfig paths, babel and webpack  aliases, workspaces, subpath imports, ...) some of which  will need configuration. Dependency-cruiser's `--init` will detect most of these for you and save them in a configuration file. 

_That said_ even with these complication it's possible to run dependency-cruiser with `npx`
- For JavaScript-only projects without any path re-mapping tomfoolery this typically works out of the box already (with some caveats)
- For other projects you'd can pass the compilers you need as arguments to `npx`.
- Locations of configurations  (babel, webpack, typescript configurations) you can pass as arguments to dependency-cruiser.

Mileage may vary, though.

Some examples:
```shell
# list all dependencies in src in text format
npx --package typescript --package dependency-cruiser -- \
    depcruise src --no-config --include-only ^src --ts-config tsconfig.json --output-type text
# npx will ask if it's OK to install typescript and dependency-cruiser; 
# hit enter to confirm

# list all dependencies in src and use the experimental 
# x-dot-webpage reporter to generate a webpage with a graph 
# of the dependencies with the native graphviz' dot
# command  + show  it  in the  browser with the `browser` command/ script
npx --package typescript --package dependency-cruiser -- \
    depcruise src --no-config --include-only ^src --ts-config tsconfig.json --output-type x-dot-webpage > dependencies.html
```
