### ISSUE TITLE
Question: using API for extracting a file

### ISSUE THREAD

**Issue by onnoomg** [sverweij/dependency-cruiser#967]
1. When I use the API to extract file dependencies, incomplete extraction occurs. The specific situation is as follows. First, I used an alias in the file (used in tsconfig, and used the API method extractTSConfig to generate a tsconfig object and pass it into cruise) and the reference conformed to the ts specification. e.g. import xxx from /@/cards/xxxx (actually referenced /@/cards/xxxx/index.ts). 
However, I found that in this case, when using cli, the full path and information can be obtained normally. But the information cannot be obtained using the API method. Through the breakpoint, I found that the followable parameter is false. Is it because of my configuration problem?

2. I would like to ask, what is the role of the tsconfig part of the extraction dependency? Because by reading the source code, I found that tsconfig is not frequently used in parsing.

looking forward to someone can help me, ThX!!!!

- Version used: 16.6
- Node version: 18.20
- Operating System and version: mac

**Comment by sverweij** [comment]
Hi @onnoomg before passing the tsconfig to the cruise method it first has to be processed with the `extractTSConfig` method. At the bottom of the [API doc](https://github.com/sverweij/dependency-cruiser/blob/main/doc/api.md) you'll find an example. 

> what is the role of the tsconfig part of the extraction dependency? Because by reading the source code, I found that tsconfig is not frequently used in parsing.

For two things:
- when resolving imported names to files on disk the resolver uses it for the aliases in it.
- it's passed to the typescript compiler (assuming that's the one available in your situation (?)) when dependency-cruiser is configured to transpile typescript down to javascript. This happens when the `tsPreCompilationDeps` option is either on `false` (the default) on `"specify"` or not passed at all.

--> What's the reason you're using the API instead of the cli?

**Comment by onnoomg** [comment]
Hi @sverweij Thanks for your reply, I’ve already used the function extractTSConfig method to process the tsconfig json file and pass it into the cruise Object. Unfortunately, I think the compiler is not working in this situation. Because the path wasn’t resolved(this path /@/card/xxxx), it at least should be resolved base on the baseDir and the tsconfig. 
 
Forgive me writing this outside😅
